/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;
import Entidades.Proveedor;
import Logica.ProveeedorManager;
import Presentacion.Modelos.ModeloComboboxTipoDocumento;
import Presentacion.Modelos.ModeloTablaProveedor;
import java.awt.BorderLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Amir Altamirano
 */
public class GestionProveedor extends javax.swing.JInternalFrame {
     private static GestionProveedor proveedor;
    
    ProveeedorManager pm=new ProveeedorManager();
    ModeloTablaProveedor mtp=new ModeloTablaProveedor();
    /**
     * Creates new form GestionProveedor
     */
    private GestionProveedor() {
        initComponents();
        CargarTabla();



        
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        this.setBorder(null);
        
        
        ModeloTablaProveedor modelo = new ModeloTablaProveedor();
        JTable tabla = new JTable(modelo);

        // Ajuste para que se expanda verticalmente
        tabla.setFillsViewportHeight(true);

        // ScrollPane que contendrá la tabla
        JScrollPane scroll = new JScrollPane(tabla);

        // Panel contenedor con BorderLayout
        JPanel panel = new JPanel(new BorderLayout());
        panel.add(scroll, BorderLayout.CENTER);

// Agrega el panel al InternalFrame
this.getContentPane().add(panel);  // si estás dentro de JInternalFrame

}
     public static GestionProveedor getProveedor(){
     if(proveedor == null || proveedor.isClosed()){
     proveedor = new GestionProveedor();

     }
     return proveedor;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TFNombre = new javax.swing.JTextField();
        TFDireccion = new javax.swing.JTextField();
        TFCorreo = new javax.swing.JTextField();
        TFContacto = new javax.swing.JTextField();
        BTRegistrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TFRuc = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        BTCancelar = new javax.swing.JButton();
        BTNuevo = new javax.swing.JButton();
        BTCerrar = new javax.swing.JButton();
        panelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBListadaProveedores = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setClosable(true);
        setForeground(java.awt.Color.white);
        setMaximizable(true);
        setFocusable(false);
        setOpaque(true);
        setVisible(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Proveedor.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Roboto SemiCondensed ExtraBold", 1, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Roboto SemiCondensed ExtraBold", 1, 14)); // NOI18N
        jLabel3.setText("Direccion:");

        jLabel4.setFont(new java.awt.Font("Roboto SemiCondensed ExtraBold", 1, 14)); // NOI18N
        jLabel4.setText("Correo:");

        jLabel5.setFont(new java.awt.Font("Roboto SemiCondensed ExtraBold", 1, 14)); // NOI18N
        jLabel5.setText("Contacto:");

        TFNombre.setBackground(new java.awt.Color(204, 204, 255));
        TFNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TFNombre.setForeground(new java.awt.Color(255, 255, 255));
        TFNombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        TFDireccion.setBackground(new java.awt.Color(204, 204, 255));
        TFDireccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TFDireccion.setForeground(new java.awt.Color(255, 255, 255));
        TFDireccion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        TFCorreo.setBackground(new java.awt.Color(204, 204, 255));
        TFCorreo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TFCorreo.setForeground(new java.awt.Color(255, 255, 255));
        TFCorreo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        TFContacto.setBackground(new java.awt.Color(204, 204, 255));
        TFContacto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TFContacto.setForeground(new java.awt.Color(255, 255, 255));
        TFContacto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TFContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFContactoActionPerformed(evt);
            }
        });

        BTRegistrar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        BTRegistrar.setText("Registrar");
        BTRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTRegistrarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Proveedores      ");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        jLabel7.setFont(new java.awt.Font("Roboto SemiCondensed ExtraBold", 1, 14)); // NOI18N
        jLabel7.setText("Ruc:");

        TFRuc.setBackground(new java.awt.Color(204, 204, 255));
        TFRuc.setForeground(new java.awt.Color(255, 255, 255));
        TFRuc.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFRuc, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TFRuc, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TFCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TFContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(BTRegistrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        BTCancelar.setBackground(new java.awt.Color(158, 110, 245));
        BTCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BTCancelar.setForeground(new java.awt.Color(255, 255, 255));
        BTCancelar.setText("Cancelar");

        BTNuevo.setBackground(new java.awt.Color(158, 110, 245));
        BTNuevo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BTNuevo.setForeground(new java.awt.Color(255, 255, 255));
        BTNuevo.setText("Nuevo");

        BTCerrar.setBackground(new java.awt.Color(158, 110, 245));
        BTCerrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BTCerrar.setForeground(new java.awt.Color(255, 255, 255));
        BTCerrar.setText("Cerrar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(BTNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(BTCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTCancelar)
                    .addComponent(BTNuevo)
                    .addComponent(BTCerrar))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        panelTabla.setBackground(new java.awt.Color(204, 204, 255));
        panelTabla.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));

        jScrollPane1.setBackground(new java.awt.Color(190, 147, 234));

        TBListadaProveedores.setModel(this.mtp);
        TBListadaProveedores.setGridColor(new java.awt.Color(178, 124, 234));
        TBListadaProveedores.setSelectionBackground(new java.awt.Color(178, 124, 234));
        jScrollPane1.setViewportView(TBListadaProveedores);

        javax.swing.GroupLayout panelTablaLayout = new javax.swing.GroupLayout(panelTabla);
        panelTabla.setLayout(panelTablaLayout);
        panelTablaLayout.setHorizontalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTablaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTablaLayout.setVerticalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFContactoActionPerformed

    private void BTRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTRegistrarActionPerformed
        Proveedor proveedor=new Proveedor();
        if(TFNombre.getText()!=""&&
           TFRuc.getText()!=""&&
           TFDireccion.getText()!=""&&
           TFCorreo.getText()!=""&&
           TFContacto.getText()!=""
                ){
            proveedor.setNombre(TFNombre.getText());
            proveedor.setRuc(TFRuc.getText());
            proveedor.setCorreo(TFCorreo.getText());
            proveedor.setDireccion(TFDireccion.getText());
            proveedor.setContacto(TFCorreo.getText());
            
            if (pm.validarDatos(proveedor)) {
                try {
                    pm.crear(proveedor);
                    CargarTabla();
                    limpiarCampos();
                } catch (SQLException ex) {
                     JOptionPane.showMessageDialog(null, "No se pudo crear el nuevo proveedor");
                }
            }else{ JOptionPane.showMessageDialog(null, "el ruc debe ser solo numeros y tener 11 digitos");}
        }else{ JOptionPane.showMessageDialog(null, "Debe rellenar todos los campos");}
    }//GEN-LAST:event_BTRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTCancelar;
    private javax.swing.JButton BTCerrar;
    private javax.swing.JButton BTNuevo;
    private javax.swing.JButton BTRegistrar;
    private javax.swing.JTable TBListadaProveedores;
    private javax.swing.JTextField TFContacto;
    private javax.swing.JTextField TFCorreo;
    private javax.swing.JTextField TFDireccion;
    private javax.swing.JTextField TFNombre;
    private javax.swing.JTextField TFRuc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelTabla;
    // End of variables declaration//GEN-END:variables
    
    public void CargarTabla(){
        try {
            mtp.setListadoProveedor(pm.lista());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Nose pudo cargar la tabla");
        }
    }
    
    public void limpiarCampos() {
        TFNombre.setText("");
        TFRuc.setText("");
        TFDireccion.setText("");
        TFCorreo.setText("");
        TFContacto.setText("");
    }


}
