/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;

import Entidades.Producto;
import Logica.ProductoManager;
import Presentacion.Modelos.ModeloTablaProducto;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.datatransfer.DataFlavor;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.TransferHandler;
/**
 *
 * @author Amir Altamirano
 */
public class GestionProducto extends javax.swing.JInternalFrame {

    private ProductoManager pm;
    private ModeloTablaProducto modeloTablaProducto =new ModeloTablaProducto();;
    /**
     * Creates new form GestionProducto
     */
    public GestionProducto() {
        initComponents();
        pm=new ProductoManager();
       
        /*FUNCION DE GUARDADO DE IMAGEN*/
        
        lblImagen.setHorizontalAlignment(SwingConstants.CENTER);
        lblImagen.setText("Arrastra aquí una imagen");
        lblImagen.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        lblImagen.setTransferHandler(new TransferHandler() {
        public boolean canImport(TransferHandler.TransferSupport support) {
            return support.isDataFlavorSupported(DataFlavor.javaFileListFlavor);
        }

        public boolean importData(TransferHandler.TransferSupport support) {
                try {
                    List<File> archivos = (List<File>) support.getTransferable().getTransferData(DataFlavor.javaFileListFlavor);
                    File archivo = archivos.get(0);
                    BufferedImage imagen = ImageIO.read(archivo);
                    
                    if (imagen == null) {
                        JOptionPane.showMessageDialog(null, "Archivo no es una imagen válida.");
                        return false;
                    }
                    String nombre = archivo.getName().toLowerCase();
                    if (!(nombre.endsWith(".png") || nombre.endsWith(".jpg") || nombre.endsWith(".jpeg") || nombre.endsWith(".bmp"))) {
                        JOptionPane.showMessageDialog(null, "Solo se permiten imágenes PNG, JPG, BMP.");
                        return false;
                    }

                    // Redimensionar imagen
                    Image escalada = imagen.getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_SMOOTH);
                    lblImagen.setIcon(new ImageIcon(escalada));
                    lblImagen.setText("");

                    // Confirmar guardar
                    /*int opcion = JOptionPane.showConfirmDialog(null, "¿Guardar esta imagen?", "Confirmar", JOptionPane.YES_NO_OPTION);
                    if (opcion == JOptionPane.YES_OPTION) {
                        File carpeta = new File("imagenes");
                        if (!carpeta.exists()) carpeta.mkdir();

                        String extension = archivo.getName().substring(archivo.getName().lastIndexOf('.') + 1);
                        File destino = new File(carpeta, "img_" + System.currentTimeMillis() + "." + extension);
                        ImageIO.write(imagen, extension, destino);
                        txtRutaGuardada.setText(destino.getAbsolutePath());
                    } else {
                        lblImagen.setIcon(null);
                        lblImagen.setText("Arrastra aquí una imagen");
                        txtRutaGuardada.setText("");
                    }*/

                    return true;
                } catch (Exception ex) {
                    ex.printStackTrace();
                    return false;
                }
            }
        });
        cargarTabla();
        this.LayeredRegistro_producto.setVisible(false);
        this.LayeredRegistro_producto.setSize(0, 499);
        this.LayeredVerProducto.setVisible(false);
        this.LayeredVerProducto.setSize(0, 450);
        Dimension sizeDimension=CalcularDimenciones();
        this.setSize(sizeDimension.width, sizeDimension.height);
        System.out.println("se esta maximisado"+ this.isMaximum());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LBLogoProducto = new javax.swing.JLabel();
        LayeredRegistro_producto = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        TFNombre = new javax.swing.JTextField();
        lblImagen = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SPPrecioCompra = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        SPPrecioVenta = new javax.swing.JSpinner();
        Registrar = new javax.swing.JButton();
        BTCancelarRegistro = new javax.swing.JButton();
        LayeredListaProductos = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        BTModificar = new javax.swing.JButton();
        BTVerDatos = new javax.swing.JButton();
        BTEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBListaProductos = new javax.swing.JTable();
        BTNuevo = new javax.swing.JButton();
        LayeredVerProducto = new javax.swing.JLayeredPane();
        LBNombre_producto = new javax.swing.JLabel();
        LBVerImagen = new javax.swing.JLabel();
        LBPrecioVenta = new javax.swing.JLabel();
        LBPrecioCompra = new javax.swing.JLabel();
        BTCerrarVer = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);

        jPanel1.setBackground(new java.awt.Color(190, 147, 234));

        LBLogoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/productos.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");

        TFNombre.setBackground(new java.awt.Color(190, 147, 234));
        TFNombre.setForeground(new java.awt.Color(255, 255, 255));
        TFNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        lblImagen.setForeground(new java.awt.Color(0, 0, 0));
        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen.setText("Ingresa imagen");
        lblImagen.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Precion Compra:");
        jLabel3.setToolTipText("");

        SPPrecioCompra.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 0.5f));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Precio Venta:");

        SPPrecioVenta.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 0.5f));

        Registrar.setBackground(new java.awt.Color(154, 82, 216));
        Registrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Registrar.setForeground(new java.awt.Color(255, 255, 255));
        Registrar.setText("Registrar");
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });

        BTCancelarRegistro.setBackground(new java.awt.Color(154, 82, 216));
        BTCancelarRegistro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BTCancelarRegistro.setForeground(new java.awt.Color(255, 255, 255));
        BTCancelarRegistro.setText("X");
        BTCancelarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTCancelarRegistroActionPerformed(evt);
            }
        });

        LayeredRegistro_producto.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredRegistro_producto.setLayer(TFNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredRegistro_producto.setLayer(lblImagen, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredRegistro_producto.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredRegistro_producto.setLayer(SPPrecioCompra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredRegistro_producto.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredRegistro_producto.setLayer(SPPrecioVenta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredRegistro_producto.setLayer(Registrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredRegistro_producto.setLayer(BTCancelarRegistro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout LayeredRegistro_productoLayout = new javax.swing.GroupLayout(LayeredRegistro_producto);
        LayeredRegistro_producto.setLayout(LayeredRegistro_productoLayout);
        LayeredRegistro_productoLayout.setHorizontalGroup(
            LayeredRegistro_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayeredRegistro_productoLayout.createSequentialGroup()
                .addGroup(LayeredRegistro_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LayeredRegistro_productoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(LayeredRegistro_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LayeredRegistro_productoLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(LayeredRegistro_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(LayeredRegistro_productoLayout.createSequentialGroup()
                                    .addComponent(Registrar)
                                    .addGap(46, 46, 46)
                                    .addComponent(BTCancelarRegistro))
                                .addGroup(LayeredRegistro_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(LayeredRegistro_productoLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(SPPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(LayeredRegistro_productoLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(SPPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(LayeredRegistro_productoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        LayeredRegistro_productoLayout.setVerticalGroup(
            LayeredRegistro_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayeredRegistro_productoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(LayeredRegistro_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(LayeredRegistro_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(SPPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(LayeredRegistro_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SPPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(41, 41, 41)
                .addGroup(LayeredRegistro_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Registrar)
                    .addComponent(BTCancelarRegistro))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Lista de productos");

        BTModificar.setBackground(new java.awt.Color(154, 82, 216));
        BTModificar.setForeground(new java.awt.Color(255, 255, 255));
        BTModificar.setText("Modificar");
        BTModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTModificarActionPerformed(evt);
            }
        });

        BTVerDatos.setBackground(new java.awt.Color(154, 82, 216));
        BTVerDatos.setForeground(new java.awt.Color(255, 255, 255));
        BTVerDatos.setText("Ver datos");
        BTVerDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTVerDatosActionPerformed(evt);
            }
        });

        BTEliminar.setBackground(new java.awt.Color(154, 82, 216));
        BTEliminar.setForeground(new java.awt.Color(255, 255, 255));
        BTEliminar.setText("Eliminar");

        jScrollPane2.setBackground(new java.awt.Color(190, 147, 234));

        TBListaProductos.setBackground(new java.awt.Color(175, 119, 234));
        TBListaProductos.setModel(this.modeloTablaProducto);
        jScrollPane1.setViewportView(TBListaProductos);

        jScrollPane2.setViewportView(jScrollPane1);

        BTNuevo.setBackground(new java.awt.Color(154, 82, 216));
        BTNuevo.setForeground(new java.awt.Color(255, 255, 255));
        BTNuevo.setText("Nuevo");
        BTNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNuevoActionPerformed(evt);
            }
        });

        LayeredListaProductos.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredListaProductos.setLayer(BTModificar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredListaProductos.setLayer(BTVerDatos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredListaProductos.setLayer(BTEliminar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredListaProductos.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredListaProductos.setLayer(BTNuevo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout LayeredListaProductosLayout = new javax.swing.GroupLayout(LayeredListaProductos);
        LayeredListaProductos.setLayout(LayeredListaProductosLayout);
        LayeredListaProductosLayout.setHorizontalGroup(
            LayeredListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayeredListaProductosLayout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(LayeredListaProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(LayeredListaProductosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTNuevo)
                .addGap(18, 18, 18)
                .addComponent(BTModificar)
                .addGap(62, 62, 62)
                .addComponent(BTVerDatos)
                .addGap(100, 100, 100)
                .addComponent(BTEliminar)
                .addGap(50, 50, 50))
        );
        LayeredListaProductosLayout.setVerticalGroup(
            LayeredListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayeredListaProductosLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(LayeredListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTModificar)
                    .addComponent(BTVerDatos)
                    .addComponent(BTEliminar)
                    .addComponent(BTNuevo))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        LayeredVerProducto.setAutoscrolls(true);
        LayeredVerProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LayeredVerProducto.setOpaque(true);

        LBNombre_producto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBNombre_producto.setForeground(new java.awt.Color(255, 255, 255));
        LBNombre_producto.setText("Nombre de producto");

        LBVerImagen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBVerImagen.setForeground(new java.awt.Color(255, 255, 255));
        LBVerImagen.setText("Imagen de profucto");
        LBVerImagen.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        LBVerImagen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        LBPrecioVenta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBPrecioVenta.setForeground(new java.awt.Color(255, 255, 255));
        LBPrecioVenta.setText("Precio de venta: S/");

        LBPrecioCompra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBPrecioCompra.setForeground(new java.awt.Color(255, 255, 255));
        LBPrecioCompra.setText("Precio de compra: S/");

        BTCerrarVer.setBackground(new java.awt.Color(154, 82, 216));
        BTCerrarVer.setForeground(new java.awt.Color(255, 255, 255));
        BTCerrarVer.setText("X");
        BTCerrarVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTCerrarVerActionPerformed(evt);
            }
        });

        LayeredVerProducto.setLayer(LBNombre_producto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredVerProducto.setLayer(LBVerImagen, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredVerProducto.setLayer(LBPrecioVenta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredVerProducto.setLayer(LBPrecioCompra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredVerProducto.setLayer(BTCerrarVer, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout LayeredVerProductoLayout = new javax.swing.GroupLayout(LayeredVerProducto);
        LayeredVerProducto.setLayout(LayeredVerProductoLayout);
        LayeredVerProductoLayout.setHorizontalGroup(
            LayeredVerProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayeredVerProductoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(LayeredVerProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBPrecioCompra)
                    .addComponent(LBPrecioVenta)
                    .addComponent(LBVerImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LayeredVerProductoLayout.createSequentialGroup()
                        .addComponent(LBNombre_producto)
                        .addGap(18, 18, 18)
                        .addComponent(BTCerrarVer)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        LayeredVerProductoLayout.setVerticalGroup(
            LayeredVerProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayeredVerProductoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(LayeredVerProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBNombre_producto)
                    .addComponent(BTCerrarVer))
                .addGap(53, 53, 53)
                .addComponent(LBVerImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(LBPrecioVenta)
                .addGap(34, 34, 34)
                .addComponent(LBPrecioCompra)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(LBLogoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LayeredRegistro_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LayeredListaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LayeredVerProducto)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LBLogoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LayeredListaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LayeredRegistro_producto)))
                    .addComponent(LayeredVerProducto, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTCancelarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTCancelarRegistroActionPerformed
        this.LayeredRegistro_producto.setVisible(false);
        this.LayeredRegistro_producto.setSize(0, 499);
        if (!this.isMaximum()) {
            Dimension sizeDimension=CalcularDimenciones();
            this.setSize(sizeDimension.width, sizeDimension.height);
        }
        //[281, 499]
    }//GEN-LAST:event_BTCancelarRegistroActionPerformed

    private void BTModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTModificarActionPerformed
        System.out.println("se esta maximisado"+ this.isMaximum());
        this.LayeredRegistro_producto.setVisible(true);
        this.LayeredRegistro_producto.setSize(218, 499);
        if (!this.isMaximum()) {
            Dimension sizeDimension=CalcularDimenciones();
            this.setSize(sizeDimension.width, sizeDimension.height);
        }
        
    }//GEN-LAST:event_BTModificarActionPerformed

    private void BTVerDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTVerDatosActionPerformed
        int fila = TBListaProductos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto de la tabla.");
            return;
        }

        // Obtener el producto seleccionado
        Producto producto = modeloTablaProducto.getProductoEn(fila);

        // Mostrar datos en la interfaz
        LBNombre_producto.setText(producto.getNombre());
        LBPrecioCompra.setText("Precio de compra: S/ " + producto.getPrecioCompra());
        LBPrecioVenta.setText("Precio de venta: S/ " + producto.getPrecioVenta());

        // Cargar imagen si tiene
        if (producto.getUrl() != null && !producto.getUrl().isEmpty()) {
            File archivo = new File(producto.getUrl());
            if (archivo.exists()) {
                try {
                    BufferedImage imagen = ImageIO.read(archivo);
                    Image escalada = imagen.getScaledInstance(LBVerImagen.getWidth(), LBVerImagen.getHeight(), Image.SCALE_SMOOTH);
                    LBVerImagen.setIcon(new ImageIcon(escalada));
                    LBVerImagen.setText("");
                } catch (Exception e) {
                    LBVerImagen.setText("Error al cargar imagen");
                    LBVerImagen.setIcon(null);
                }
            } else {
                LBVerImagen.setText("Imagen no encontrada");
                LBVerImagen.setIcon(null);
            }
        } else {
            LBVerImagen.setText("Sin imagen");
            LBVerImagen.setIcon(null);
        }

        // Mostrar el panel
        LayeredVerProducto.setVisible(true);
        LayeredVerProducto.setSize(328, 450);
        if (!this.isMaximum()) {
            Dimension sizeDimension = CalcularDimenciones();
            this.setSize(sizeDimension.width, sizeDimension.height);
        }
    }//GEN-LAST:event_BTVerDatosActionPerformed

    private void BTCerrarVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTCerrarVerActionPerformed
        this.LayeredVerProducto.setVisible(false);
        //[328, 450]
        this.LayeredVerProducto.setSize(0, 450);
        if (!this.isMaximum()) {
            Dimension sizeDimension=CalcularDimenciones();
            this.setSize(sizeDimension.width, sizeDimension.height);
        }
    }//GEN-LAST:event_BTCerrarVerActionPerformed

    private void BTNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNuevoActionPerformed
        System.out.println("se esta maximisado"+ this.isMaximum());
        this.LayeredRegistro_producto.setVisible(true);
        this.LayeredRegistro_producto.setSize(218, 499);
        if (!this.isMaximum()) {
            Dimension sizeDimension=CalcularDimenciones();
            this.setSize(sizeDimension.width, sizeDimension.height);
        }
    }//GEN-LAST:event_BTNuevoActionPerformed

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
        Producto producto=new Producto();
        producto.setNombre(this.TFNombre.getText());
        producto.setPrecioCompra((float) this.SPPrecioCompra.getValue());
        producto.setPrecioVenta((float) this.SPPrecioVenta.getValue());
        producto.setUrl(pm.guardarImagen(obtenerImagenDeLabel()));
        pm.registrarProducto(producto);
        cargarTabla();
        limpiarCampos();
    }//GEN-LAST:event_RegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTCancelarRegistro;
    private javax.swing.JButton BTCerrarVer;
    private javax.swing.JButton BTEliminar;
    private javax.swing.JButton BTModificar;
    private javax.swing.JButton BTNuevo;
    private javax.swing.JButton BTVerDatos;
    private javax.swing.JLabel LBLogoProducto;
    private javax.swing.JLabel LBNombre_producto;
    private javax.swing.JLabel LBPrecioCompra;
    private javax.swing.JLabel LBPrecioVenta;
    private javax.swing.JLabel LBVerImagen;
    private javax.swing.JLayeredPane LayeredListaProductos;
    private javax.swing.JLayeredPane LayeredRegistro_producto;
    private javax.swing.JLayeredPane LayeredVerProducto;
    private javax.swing.JButton Registrar;
    private javax.swing.JSpinner SPPrecioCompra;
    private javax.swing.JSpinner SPPrecioVenta;
    private javax.swing.JTable TBListaProductos;
    private javax.swing.JTextField TFNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblImagen;
    // End of variables declaration//GEN-END:variables
    
    
    public BufferedImage obtenerImagenDeLabel() {
        if (lblImagen.getIcon() != null && lblImagen.getIcon() instanceof ImageIcon) {
            Image imagen = ((ImageIcon) lblImagen.getIcon()).getImage();

            // Crear un BufferedImage compatible con la imagen
            BufferedImage buffered = new BufferedImage(
                imagen.getWidth(null),
                imagen.getHeight(null),
                BufferedImage.TYPE_INT_ARGB // Puedes usar TYPE_INT_RGB si no necesitas transparencia
            );

            // Dibujar la imagen en el BufferedImage
            buffered.getGraphics().drawImage(imagen, 0, 0, null);
            return buffered;
        }
        return null; // No hay imagen en el label
    }

    
    public Dimension CalcularDimenciones(){
        double Width=50+LayeredListaProductos.getPreferredSize().getWidth()+ LayeredRegistro_producto.getSize().getWidth()+LayeredVerProducto.getSize().getWidth()+ LBLogoProducto.getPreferredSize().getWidth();
        double Height=593;
        
        
        Dimension size=new Dimension((int)Width,(int)Height);
        return  size;
    }
    
    public void cargarTabla(){
        try {
            modeloTablaProducto.setListadoProducto(pm.cargarProductosActivos());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    public void limpiarCampos() {
        TFNombre.setText("");
        SPPrecioCompra.setValue(0.0f);
        SPPrecioVenta.setValue(0.0f);

        lblImagen.setIcon(null);
        lblImagen.setText("Arrastra aquí una imagen");
    }


}
