/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;

import Entidades.Producto;
import Logica.ProductoManager;
import Presentacion.Modelos.ModeloTablaProducto;
import Presentacion.Modelos.ModeloComboboxProveedores;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.datatransfer.DataFlavor;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.TransferHandler;
import Logica.ProveeedorManager;
import javax.swing.plaf.basic.BasicInternalFrameUI;
/**
 *
 * @author Amir Altamirano
 */
public class GestionProducto extends javax.swing.JInternalFrame {

    private static GestionProducto producto;

    private ProductoManager pm;
    private ProveeedorManager proveeedorManager;
    private ModeloTablaProducto modeloTablaProducto =new ModeloTablaProducto();
    private ModeloComboboxProveedores comboboxProveedor= new ModeloComboboxProveedores();
    /**
     * Creates new form GestionProducto
     */
    private GestionProducto() {

        BasicInternalFrameUI uli = (BasicInternalFrameUI)this.getUI();
        uli.setNorthPane(null);
        this.setBorder(null);
        
        

        this.comboboxProveedor = new ModeloComboboxProveedores();
        initComponents();
        pm=new ProductoManager();
        proveeedorManager= new ProveeedorManager();
       
        /*FUNCION DE GUARDADO DE IMAGEN*/
        
        lblImagen.setHorizontalAlignment(SwingConstants.CENTER);
        lblImagen.setText("Arrastra aquí una imagen");
        lblImagen.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        lblImagen.setTransferHandler(new TransferHandler() {
        @Override
        public boolean canImport(TransferHandler.TransferSupport support) {
            return support.isDataFlavorSupported(DataFlavor.javaFileListFlavor);
        }

        @Override
        public boolean importData(TransferHandler.TransferSupport support) {
                try {
                    List<File> archivos = (List<File>) support.getTransferable().getTransferData(DataFlavor.javaFileListFlavor);
                    File archivo = archivos.get(0);
                    BufferedImage imagen = ImageIO.read(archivo);
                    
                    if (imagen == null) {
                        JOptionPane.showMessageDialog(null, "Archivo no es una imagen válida.");
                        return false;
                    }
                    String nombre = archivo.getName().toLowerCase();
                    if (!(nombre.endsWith(".png") || nombre.endsWith(".jpg") || nombre.endsWith(".jpeg") || nombre.endsWith(".bmp"))) {
                        JOptionPane.showMessageDialog(null, "Solo se permiten imágenes PNG, JPG, BMP.");
                        return false;
                    }

                    // Redimensionar imagen
                    Image escalada = imagen.getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_SMOOTH);
                    lblImagen.setIcon(new ImageIcon(escalada));
                    lblImagen.setText("");


                    return true;
                } catch (Exception ex) {
                    ex.printStackTrace();
                    return false;
                }
            }
        });
        cargarTabla();
        CargarCombobox();
        this.LayeredRegistro_producto.setVisible(false);
        this.LayeredRegistro_producto.setSize(0, 499);
        this.LayeredVerProducto.setVisible(false);
        this.LayeredVerProducto.setSize(0, 450);
        Dimension sizeDimension=CalcularDimenciones();
        this.setSize(sizeDimension.width, sizeDimension.height);
        System.out.println("se esta maximisado"+ this.isMaximum());
        
    }

     public static GestionProducto getProducto(){

     if(producto == null || producto.isClosed()){
     producto = new GestionProducto();
     }
     return producto;

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LayeredRegistro_producto = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        TFNombre = new javax.swing.JTextField();
        lblImagen = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SPPrecioCompra = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        SPPrecioVenta = new javax.swing.JSpinner();
        Registrar = new javax.swing.JButton();
        BTCancelarRegistro = new javax.swing.JButton();
        CBProveedores = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        LayeredListaProductos = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        BTModificar = new javax.swing.JButton();
        BTVerDatos = new javax.swing.JButton();
        BTEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBListaProductos = new javax.swing.JTable();
        BTNuevo = new javax.swing.JButton();
        LayeredVerProducto = new javax.swing.JLayeredPane();
        LBNombre_producto = new javax.swing.JLabel();
        LBVerImagen = new javax.swing.JLabel();
        LBPrecioVenta = new javax.swing.JLabel();
        LBPrecioCompra = new javax.swing.JLabel();
        BTCerrarVer = new javax.swing.JButton();
        LBProveedor = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setMaximizable(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        LayeredRegistro_producto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("Nombre:");

        TFNombre.setBackground(new java.awt.Color(204, 204, 255));
        TFNombre.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        TFNombre.setForeground(new java.awt.Color(255, 255, 255));
        TFNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        lblImagen.setBackground(new java.awt.Color(255, 255, 255));
        lblImagen.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add_16750539.png"))); // NOI18N

        lblImagen.setBorder(new javax.swing.border.MatteBorder(null));
        lblImagen.setRequestFocusEnabled(false);
        lblImagen.setVerifyInputWhenFocusTarget(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("Precion Compra:");
        jLabel3.setToolTipText("");

        SPPrecioCompra.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 0.5f));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("Precio Venta:");

        SPPrecioVenta.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 0.5f));

        Registrar.setBackground(new java.awt.Color(153, 153, 255));
        Registrar.setText("Registrar");
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });

        BTCancelarRegistro.setBackground(new java.awt.Color(153, 153, 255));
        BTCancelarRegistro.setText("X");
        BTCancelarRegistro.setPreferredSize(new java.awt.Dimension(25, 25));
        BTCancelarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTCancelarRegistroActionPerformed(evt);
            }
        });

        CBProveedores.setModel(this.comboboxProveedor);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setText("Proveedor");
        jLabel5.setToolTipText("");

        LayeredRegistro_producto.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredRegistro_producto.setLayer(TFNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredRegistro_producto.setLayer(lblImagen, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredRegistro_producto.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredRegistro_producto.setLayer(SPPrecioCompra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredRegistro_producto.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredRegistro_producto.setLayer(SPPrecioVenta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredRegistro_producto.setLayer(Registrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredRegistro_producto.setLayer(BTCancelarRegistro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredRegistro_producto.setLayer(CBProveedores, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredRegistro_producto.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout LayeredRegistro_productoLayout = new javax.swing.GroupLayout(LayeredRegistro_producto);
        LayeredRegistro_producto.setLayout(LayeredRegistro_productoLayout);
        LayeredRegistro_productoLayout.setHorizontalGroup(
            LayeredRegistro_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayeredRegistro_productoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(LayeredRegistro_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LayeredRegistro_productoLayout.createSequentialGroup()
                        .addComponent(Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(LayeredRegistro_productoLayout.createSequentialGroup()
                        .addGroup(LayeredRegistro_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LayeredRegistro_productoLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LayeredRegistro_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LayeredRegistro_productoLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CBProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LayeredRegistro_productoLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SPPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LayeredRegistro_productoLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(SPPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 12, Short.MAX_VALUE))))
            .addGroup(LayeredRegistro_productoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTCancelarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        LayeredRegistro_productoLayout.setVerticalGroup(
            LayeredRegistro_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayeredRegistro_productoLayout.createSequentialGroup()
                .addComponent(BTCancelarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(LayeredRegistro_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(LayeredRegistro_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(SPPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(LayeredRegistro_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SPPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(LayeredRegistro_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Lista de productos");

        BTModificar.setBackground(new java.awt.Color(153, 153, 255));
        BTModificar.setText("Modificar");
        BTModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTModificarActionPerformed(evt);
            }
        });

        BTVerDatos.setBackground(new java.awt.Color(153, 153, 255));
        BTVerDatos.setText("Ver datos");
        BTVerDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTVerDatosActionPerformed(evt);
            }
        });

        BTEliminar.setBackground(new java.awt.Color(153, 153, 255));
        BTEliminar.setText("Eliminar");

        jScrollPane2.setBackground(new java.awt.Color(190, 147, 234));

        TBListaProductos.setModel(this.modeloTablaProducto);
        jScrollPane1.setViewportView(TBListaProductos);

        jScrollPane2.setViewportView(jScrollPane1);

        BTNuevo.setBackground(new java.awt.Color(153, 153, 255));
        BTNuevo.setText("Nuevo");
        BTNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNuevoActionPerformed(evt);
            }
        });

        LayeredListaProductos.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredListaProductos.setLayer(BTModificar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredListaProductos.setLayer(BTVerDatos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredListaProductos.setLayer(BTEliminar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredListaProductos.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredListaProductos.setLayer(BTNuevo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout LayeredListaProductosLayout = new javax.swing.GroupLayout(LayeredListaProductos);
        LayeredListaProductos.setLayout(LayeredListaProductosLayout);
        LayeredListaProductosLayout.setHorizontalGroup(
            LayeredListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayeredListaProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(LayeredListaProductosLayout.createSequentialGroup()
                .addGroup(LayeredListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                    .addGroup(LayeredListaProductosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BTNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTVerDatos)
                        .addGap(200, 200, 200)
                        .addComponent(BTModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTEliminar)))
                .addContainerGap())
        );
        LayeredListaProductosLayout.setVerticalGroup(
            LayeredListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayeredListaProductosLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(LayeredListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTModificar)
                    .addComponent(BTVerDatos)
                    .addComponent(BTEliminar)
                    .addComponent(BTNuevo))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        LayeredVerProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LayeredVerProducto.setAutoscrolls(true);
        LayeredVerProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LayeredVerProducto.setOpaque(true);

        LBNombre_producto.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LBNombre_producto.setText("Nombre de producto");

        LBVerImagen.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        LBVerImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBVerImagen.setText("Imagen de profucto");
        LBVerImagen.setBorder(new javax.swing.border.MatteBorder(null));
        LBVerImagen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LBVerImagen.setVerifyInputWhenFocusTarget(false);

        LBPrecioVenta.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LBPrecioVenta.setText("Precio de venta: S/");

        LBPrecioCompra.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LBPrecioCompra.setText("Precio de compra: S/");

        BTCerrarVer.setBackground(new java.awt.Color(153, 153, 255));
        BTCerrarVer.setText("X");
        BTCerrarVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTCerrarVerActionPerformed(evt);
            }
        });

        LBProveedor.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LBProveedor.setText("Proveedor:");

        LayeredVerProducto.setLayer(LBNombre_producto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredVerProducto.setLayer(LBVerImagen, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredVerProducto.setLayer(LBPrecioVenta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredVerProducto.setLayer(LBPrecioCompra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredVerProducto.setLayer(BTCerrarVer, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredVerProducto.setLayer(LBProveedor, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout LayeredVerProductoLayout = new javax.swing.GroupLayout(LayeredVerProducto);
        LayeredVerProducto.setLayout(LayeredVerProductoLayout);
        LayeredVerProductoLayout.setHorizontalGroup(
            LayeredVerProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayeredVerProductoLayout.createSequentialGroup()
                .addGroup(LayeredVerProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LayeredVerProductoLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(LayeredVerProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBPrecioCompra)
                            .addComponent(LBPrecioVenta)
                            .addComponent(LBNombre_producto)
                            .addComponent(LBProveedor)))
                    .addGroup(LayeredVerProductoLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(LBVerImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LayeredVerProductoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BTCerrarVer))
        );
        LayeredVerProductoLayout.setVerticalGroup(
            LayeredVerProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayeredVerProductoLayout.createSequentialGroup()
                .addComponent(BTCerrarVer)
                .addGap(15, 15, 15)
                .addComponent(LBNombre_producto)
                .addGap(40, 40, 40)
                .addComponent(LBVerImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(LBPrecioVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBPrecioCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LBProveedor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(LayeredRegistro_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LayeredListaProductos)
                .addGap(50, 50, 50)
                .addComponent(LayeredVerProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LayeredRegistro_producto))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(LayeredListaProductos)
                .addContainerGap())
            .addComponent(LayeredVerProducto)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTCancelarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTCancelarRegistroActionPerformed
        this.LayeredRegistro_producto.setVisible(false);
        this.LayeredRegistro_producto.setSize(0, 499);
        if (!this.isMaximum()) {
            Dimension sizeDimension=CalcularDimenciones();
            this.setSize(sizeDimension.width, sizeDimension.height);
        }
        //[281, 499]
    }//GEN-LAST:event_BTCancelarRegistroActionPerformed

    private void BTModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTModificarActionPerformed
        System.out.println("se esta maximisado"+ this.isMaximum());
        this.LayeredRegistro_producto.setVisible(true);
        this.LayeredRegistro_producto.setSize(218, 499);
        if (!this.isMaximum()) {
            Dimension sizeDimension=CalcularDimenciones();
            this.setSize(sizeDimension.width, sizeDimension.height);
        }
        
    }//GEN-LAST:event_BTModificarActionPerformed

    private void BTVerDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTVerDatosActionPerformed
        int fila = TBListaProductos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto de la tabla.");
            return;
        }
        Producto producto = modeloTablaProducto.getProductoEn(fila);
        LBNombre_producto.setText(producto.getNombre());
        LBPrecioCompra.setText("Precio de compra: S/ " + producto.getPrecioCompra());
        LBPrecioVenta.setText("Precio de venta: S/ " + producto.getPrecioVenta());
        LBProveedor.setText("Proveedor:"+ producto.getProveedor().getNombre());

        // Cargar imagen si tiene
        if (producto.getUrl() != null && !producto.getUrl().isEmpty()) {
            File archivo = new File(producto.getUrl());
            if (archivo.exists()) {
                try {
                    BufferedImage imagen = ImageIO.read(archivo);
                    Image escalada = imagen.getScaledInstance(LBVerImagen.getWidth(), LBVerImagen.getHeight(), Image.SCALE_SMOOTH);
                    LBVerImagen.setIcon(new ImageIcon(escalada));
                    LBVerImagen.setText("");
                } catch (Exception e) {
                    LBVerImagen.setText("Error al cargar imagen");
                    LBVerImagen.setIcon(null);
                }
            } else {
                LBVerImagen.setText("Imagen no encontrada");
                LBVerImagen.setIcon(null);
            }
        } else {
            LBVerImagen.setText("Sin imagen");
            LBVerImagen.setIcon(null);
        }
        LayeredVerProducto.setVisible(true);
        LayeredVerProducto.setSize(328, 450);
        if (!this.isMaximum()) {
            Dimension sizeDimension = CalcularDimenciones();
            this.setSize(sizeDimension.width, sizeDimension.height);
        }
    }//GEN-LAST:event_BTVerDatosActionPerformed

    private void BTCerrarVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTCerrarVerActionPerformed
        this.LayeredVerProducto.setVisible(false);
        //[328, 450]
        this.LayeredVerProducto.setSize(0, 450);
        if (!this.isMaximum()) {
            Dimension sizeDimension=CalcularDimenciones();
            this.setSize(sizeDimension.width, sizeDimension.height);
        }
    }//GEN-LAST:event_BTCerrarVerActionPerformed

    private void BTNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNuevoActionPerformed
        System.out.println("se esta maximisado"+ this.isMaximum());
        this.LayeredRegistro_producto.setVisible(true);
        this.LayeredRegistro_producto.setSize(218, 499);
        if (!this.isMaximum()) {
            Dimension sizeDimension=CalcularDimenciones();
            this.setSize(sizeDimension.width, sizeDimension.height);
        }
    }//GEN-LAST:event_BTNuevoActionPerformed

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
        Producto producto=new Producto();
        producto.setNombre(this.TFNombre.getText());
        producto.setPrecioCompra((float) this.SPPrecioCompra.getValue());
        producto.setPrecioVenta((float) this.SPPrecioVenta.getValue());
        producto.setUrl(pm.guardarImagen(obtenerImagenDeLabel()));
        producto.setProveedor(comboboxProveedor.getSeleccionado());
        pm.registrarProducto(producto);
        cargarTabla();
        limpiarCampos();
    }//GEN-LAST:event_RegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTCancelarRegistro;
    private javax.swing.JButton BTCerrarVer;
    private javax.swing.JButton BTEliminar;
    private javax.swing.JButton BTModificar;
    private javax.swing.JButton BTNuevo;
    private javax.swing.JButton BTVerDatos;
    private javax.swing.JComboBox<String> CBProveedores;
    private javax.swing.JLabel LBNombre_producto;
    private javax.swing.JLabel LBPrecioCompra;
    private javax.swing.JLabel LBPrecioVenta;
    private javax.swing.JLabel LBProveedor;
    private javax.swing.JLabel LBVerImagen;
    private javax.swing.JLayeredPane LayeredListaProductos;
    private javax.swing.JLayeredPane LayeredRegistro_producto;
    private javax.swing.JLayeredPane LayeredVerProducto;
    private javax.swing.JButton Registrar;
    private javax.swing.JSpinner SPPrecioCompra;
    private javax.swing.JSpinner SPPrecioVenta;
    private javax.swing.JTable TBListaProductos;
    private javax.swing.JTextField TFNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblImagen;
    // End of variables declaration//GEN-END:variables
    
    
    public BufferedImage obtenerImagenDeLabel() {
        if (lblImagen.getIcon() != null && lblImagen.getIcon() instanceof ImageIcon) {
            Image imagen = ((ImageIcon) lblImagen.getIcon()).getImage();

            // Crear un BufferedImage compatible con la imagen
            BufferedImage buffered = new BufferedImage(
                imagen.getWidth(null),
                imagen.getHeight(null),
                BufferedImage.TYPE_INT_ARGB // Puedes usar TYPE_INT_RGB si no necesitas transparencia
            );

            // Dibujar la imagen en el BufferedImage
            buffered.getGraphics().drawImage(imagen, 0, 0, null);
            return buffered;
        }
        return null; // No hay imagen en el label
    }

    
    public Dimension CalcularDimenciones() {
    Dimension size = new Dimension(900, 600); 
    this.setPreferredSize(size);             
    this.setSize(size);                      
    return size;
}

    
    public void cargarTabla(){
        try {
            modeloTablaProducto.setListadoProducto(pm.cargarProductosActivos());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
             this.setSize(getPreferredSize());
        }
    }
    
    public void CargarCombobox(){
        try {
            this.comboboxProveedor.setListadoProveedor( proveeedorManager.lista());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    public void limpiarCampos() {
        TFNombre.setText("");
        SPPrecioCompra.setValue(0.0f);
        SPPrecioVenta.setValue(0.0f);

        lblImagen.setIcon(null);
        lblImagen.setText("Arrastra aquí una imagen");
    }


}
