/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;

import Presentacion.Modelos.ModeloComboboxTipoDocumento;
import Presentacion.Modelos.ModeloTablaCliente;
import Entidades.Cliente;
import Logica.ClienteManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import AccesoDatos.BDTipo_Documento;
import Entidades.Tipo_documento;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Amir Altamirano
 */
public class GestionClientes extends javax.swing.JInternalFrame {

    private static GestionClientes cliente;
    BDTipo_Documento bdtd = new BDTipo_Documento();
    private ModeloComboboxTipoDocumento mctd = new ModeloComboboxTipoDocumento();
    private ModeloTablaCliente modeloTablaCliente = new ModeloTablaCliente();
    private ClienteManager clienteManager = new ClienteManager();
    private Cliente clienteSeleccionado = null;

    /**
     * Creates new form GestionClientes
     */
    private GestionClientes() {
        initComponents();
        CargarTabla();
        CragarCoombobox();
        TBListaClientes.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                cargarDatosClienteSeleccionado();
            }
        });
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        this.setBorder(null);
    }

    public static GestionClientes getCliente() {
        if (cliente == null || cliente.isClosed()) {
            cliente = new GestionClientes();
        }
        return cliente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TFNroDocumento = new javax.swing.JTextField();
        TFTelefono = new javax.swing.JTextField();
        TFNombre = new javax.swing.JTextField();
        CBTipoDocumento = new javax.swing.JComboBox<>();
        BTRegistrar = new javax.swing.JButton();
        BTCancelarRegistro = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBListaClientes = new javax.swing.JTable();
        BTModificar = new javax.swing.JButton();
        BTNuevo = new javax.swing.JButton();
        BTEliminar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(190, 147, 234));
        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLayeredPane1.setBackground(new java.awt.Color(153, 153, 255));
        jLayeredPane1.setForeground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setToolTipText("");

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Nombre");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tipo documento");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("N° Documento");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Telefono");

        TFNroDocumento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TFNroDocumento.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        TFTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TFTelefono.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        TFNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TFNombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        CBTipoDocumento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBTipoDocumento.setModel(this.mctd);
        CBTipoDocumento.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        BTRegistrar.setBackground(new java.awt.Color(153, 153, 255));
        BTRegistrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BTRegistrar.setText("Registrar");
        BTRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTRegistrarActionPerformed(evt);
            }
        });

        BTCancelarRegistro.setBackground(new java.awt.Color(153, 153, 255));
        BTCancelarRegistro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BTCancelarRegistro.setText("x");
        BTCancelarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTCancelarRegistroActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TFNroDocumento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TFTelefono, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TFNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(CBTipoDocumento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(BTRegistrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(BTCancelarRegistro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TFNroDocumento)
                                .addComponent(TFTelefono)
                                .addComponent(TFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CBTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(BTRegistrar)
                        .addGap(51, 51, 51)
                        .addComponent(BTCancelarRegistro)))
                .addGap(0, 32, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CBTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TFNroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(138, 138, 138)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTRegistrar)
                    .addComponent(BTCancelarRegistro))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jScrollPane1.setBackground(new java.awt.Color(190, 147, 234));

        TBListaClientes.setModel(this.modeloTablaCliente);
        jScrollPane1.setViewportView(TBListaClientes);

        BTModificar.setBackground(new java.awt.Color(153, 153, 255));
        BTModificar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BTModificar.setText("Modificar");
        BTModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTModificarActionPerformed(evt);
            }
        });

        BTNuevo.setBackground(new java.awt.Color(153, 153, 255));
        BTNuevo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BTNuevo.setText("Nuevo");
        BTNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNuevoActionPerformed(evt);
            }
        });

        BTEliminar.setBackground(new java.awt.Color(153, 153, 255));
        BTEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BTEliminar.setText("Eliminar");
        BTEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTEliminarActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(BTModificar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(BTNuevo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(BTEliminar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(BTNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTEliminar)
                .addGap(17, 17, 17))
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTModificar)
                    .addComponent(BTNuevo)
                    .addComponent(BTEliminar))
                .addGap(17, 17, 17))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gestion de Cliente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLayeredPane2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTRegistrarActionPerformed
        // Validar que los campos no estén vacíos
        if (TFNombre.getText().isEmpty() || TFTelefono.getText().isEmpty() || TFNroDocumento.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe llenar todos los campos.", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (clienteSeleccionado == null) {
            // --- MODO REGISTRO ---
            Cliente nuevoCliente = new Cliente();
            nuevoCliente.setNombre(TFNombre.getText());
            nuevoCliente.setTelefono(TFTelefono.getText());
            nuevoCliente.setTipo_documento(mctd.getSeleccionado());
            nuevoCliente.setNro_documento(TFNroDocumento.getText());

            if (clienteManager.registrarCliente(nuevoCliente)) {
                JOptionPane.showMessageDialog(this, "Cliente registrado exitosamente.", "Registro Exitoso", JOptionPane.INFORMATION_MESSAGE);
                CargarTabla();
                limpiarFormulario();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo registrar el cliente.", "Error de Registro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // --- MODO MODIFICACIÓN ---
            clienteSeleccionado.setNombre(TFNombre.getText());
            clienteSeleccionado.setTelefono(TFTelefono.getText());
            clienteSeleccionado.setTipo_documento(mctd.getSeleccionado());
            clienteSeleccionado.setNro_documento(TFNroDocumento.getText());

            if (clienteManager.actualizarCliente(clienteSeleccionado.getId(), clienteSeleccionado)) {
                JOptionPane.showMessageDialog(this, "Cliente actualizado exitosamente.", "Actualización Exitosa", JOptionPane.INFORMATION_MESSAGE);
                CargarTabla();
                limpiarFormulario();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo actualizar el cliente.", "Error de Actualización", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_BTRegistrarActionPerformed

    private void BTEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTEliminarActionPerformed
        // TODO add your handling code here:
        if (clienteSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente de la tabla.", "Selección Requerida", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro de que desea eliminar al cliente '" + clienteSeleccionado.getNombre() + "'?",
                "Confirmar Eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (confirmacion == JOptionPane.YES_OPTION) {
            if (clienteManager.eliminarCliente(clienteSeleccionado.getId())) {
                JOptionPane.showMessageDialog(this, "Cliente eliminado exitosamente.", "Eliminación Exitosa", JOptionPane.INFORMATION_MESSAGE);
                CargarTabla();
                limpiarFormulario();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo eliminar el cliente.", "Error de Eliminación", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BTEliminarActionPerformed

    private void BTCancelarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTCancelarRegistroActionPerformed
        // TODO add your handling code here:
        limpiarFormulario();
    }//GEN-LAST:event_BTCancelarRegistroActionPerformed

    private void BTModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTModificarActionPerformed
        // TODO add your handling code here:
        if (clienteSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un cliente de la tabla para modificar.", "Selección Requerida", JOptionPane.WARNING_MESSAGE);
        } else {
            // El listener de la tabla ya carga los datos, así que este botón
            // sirve principalmente como una confirmación visual para el usuario
            // de que está a punto de modificar. Se podría habilitar/deshabilitar campos aquí si se quisiera.
            TFNombre.requestFocus(); // Pone el foco en el campo nombre para empezar a editar.
        }
    }//GEN-LAST:event_BTModificarActionPerformed

    private void BTNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNuevoActionPerformed
        // TODO add your handling code here:
        limpiarFormulario();
    }//GEN-LAST:event_BTNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTCancelarRegistro;
    private javax.swing.JButton BTEliminar;
    private javax.swing.JButton BTModificar;
    private javax.swing.JButton BTNuevo;
    private javax.swing.JButton BTRegistrar;
    private javax.swing.JComboBox<String> CBTipoDocumento;
    private javax.swing.JTable TBListaClientes;
    private javax.swing.JTextField TFNombre;
    private javax.swing.JTextField TFNroDocumento;
    private javax.swing.JTextField TFTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    public void CargarTabla() {
        try {
            modeloTablaCliente.setListadoCliente(clienteManager.listarClientesActivos());
            System.err.println("cantidad de clientes: " + clienteManager.listarClientesActivos().size());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "No se pudo cargar la tabla");
        }
    }

    public void CragarCoombobox() {
        try {
            mctd.setListadoTipoDocumento(bdtd.listar());
            System.err.println("numero de docu: " + bdtd.listar().size());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "No se pudo cargar los tipos documento");
        }
    }

    public void limpiarCampos() {
        TFNombre.setText("");
        TFTelefono.setText("");
        TFNroDocumento.setText("");
        if (CBTipoDocumento.getItemCount() > 0) {
            CBTipoDocumento.setSelectedIndex(0); // Selecciona el primer ítem
        }
    }

    private void limpiarFormulario() {
        TFNombre.setText("");
        TFTelefono.setText("");
        TFNroDocumento.setText("");
        if (CBTipoDocumento.getItemCount() > 0) {
            CBTipoDocumento.setSelectedIndex(0);
        }
        TBListaClientes.clearSelection(); // Deselecciona cualquier fila en la tabla
        this.clienteSeleccionado = null; // MUY IMPORTANTE: Resetea el estado a "nuevo registro"
        BTRegistrar.setText("Registrar"); // Devuelve el botón a su estado original
        TFNombre.requestFocus();
    }

    private void cargarDatosClienteSeleccionado() {
        int filaSeleccionada = TBListaClientes.getSelectedRow();
        if (filaSeleccionada != -1) {
            this.clienteSeleccionado = modeloTablaCliente.getCliente(filaSeleccionada);
            TFNombre.setText(clienteSeleccionado.getNombre());
            TFTelefono.setText(clienteSeleccionado.getTelefono());
            TFNroDocumento.setText(clienteSeleccionado.getNro_documento());

            // Aquí usamos el método del modelo del combobox para encontrar el índice correcto
            Tipo_documento td = clienteSeleccionado.getTipo_documento();
            if (td != null) {
                int index = mctd.getSelectTipoDocumento(td);
                CBTipoDocumento.setSelectedIndex(index);
            }

            BTRegistrar.setText("Guardar Cambios");
        }
    }

}
