/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package Presentacion;

import javax.swing.JFrame;

/**
 *
 * @author Amir Altamirano
 */
public class Importadora extends javax.swing.JFrame {

    /**
     * Creates new form Importadora
     */
    public Importadora() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setAlwaysOnTop(false); // Asegúrate de permitir otras ventanas encima

        addWindowStateListener(e -> {
            if ((e.getNewState() & JFrame.NORMAL) == JFrame.NORMAL) {
                // Restaurar tamaño normal
                this.setSize(1024, 720);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        RegistroProveedor = new javax.swing.JMenuItem();
        RegistroProducto = new javax.swing.JMenuItem();
        GestionCliente = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        RegistroVenta = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        getContentPane().add(desktopPane, java.awt.BorderLayout.CENTER);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Funciones");

        RegistroProveedor.setMnemonic('t');
        RegistroProveedor.setText("Registro de proveedores");
        RegistroProveedor.setToolTipText("");
        RegistroProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroProveedorActionPerformed(evt);
            }
        });
        editMenu.add(RegistroProveedor);

        RegistroProducto.setMnemonic('y');
        RegistroProducto.setText("Registro de productos");
        RegistroProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroProductoActionPerformed(evt);
            }
        });
        editMenu.add(RegistroProducto);

        GestionCliente.setText("GestionCliente");
        GestionCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionClienteActionPerformed(evt);
            }
        });
        editMenu.add(GestionCliente);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        RegistroVenta.setText("Registro Venta");
        RegistroVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroVentaActionPerformed(evt);
            }
        });
        editMenu.add(RegistroVenta);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Empleados");
        deleteMenuItem.setToolTipText("");
        deleteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void RegistroProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroProveedorActionPerformed
        GestionProveedor ventanaProveedor = new GestionProveedor();
        desktopPane.add(ventanaProveedor);
        ventanaProveedor.setVisible(true);
    }//GEN-LAST:event_RegistroProveedorActionPerformed

    private void RegistroProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroProductoActionPerformed
        GestionProducto ventanaProducto =new GestionProducto();
        desktopPane.add(ventanaProducto);
        ventanaProducto.setVisible(true);
    }//GEN-LAST:event_RegistroProductoActionPerformed

    private void GestionClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionClienteActionPerformed
        GestionClientes VentanaClientes=new GestionClientes();
        desktopPane.add(VentanaClientes);
        VentanaClientes.setVisible(true);
    }//GEN-LAST:event_GestionClienteActionPerformed

    private void deleteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuItemActionPerformed
        DatosEmpleado datosEmpleado=new DatosEmpleado();
        desktopPane.add(datosEmpleado);
        datosEmpleado.setVisible(true);
    }//GEN-LAST:event_deleteMenuItemActionPerformed

    private void RegistroVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroVentaActionPerformed
        RegistrarVenta VentanaRegistroVenta=new RegistrarVenta();
        desktopPane.add(VentanaRegistroVenta);
        VentanaRegistroVenta.setVisible(true);
    }//GEN-LAST:event_RegistroVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Importadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Importadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Importadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Importadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Importadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem GestionCliente;
    private javax.swing.JMenuItem RegistroProducto;
    private javax.swing.JMenuItem RegistroProveedor;
    private javax.swing.JMenuItem RegistroVenta;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
