/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;

import Entidades.Compra;
import Entidades.CompraDetalles;
import Logica.ComprasManager;
import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Amir Altamirano
 */
public class ListaCompras extends javax.swing.JInternalFrame {
    private static ListaCompras instancia;
    
    private boolean existenRegistros=false;
    private ComprasManager comprasManager=new ComprasManager();
    private ArrayList<CompraDetalles> compraDetalles=new ArrayList<>();
    private ArrayList<Compra> comprasPropuestas=new ArrayList<>();
    private JPanel contenedorCompras;
    /**
     * Creates new form ListasCompras
     */
    public ListaCompras() {
        initComponents();
        
        
        contenedorCompras = new JPanel();
        contenedorCompras.setLayout(new BoxLayout(contenedorCompras, BoxLayout.Y_AXIS));
        contenedorCompras.setBackground(new Color(190, 147, 234)); // mismo fondo

        jScrollPane1.setViewportView(contenedorCompras);
        try {
            cargarCompras(comprasManager.listar(), false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "No se pudo cargar las Compras");
        }
    }
public static ListaCompras getListaCompra() {
    if (instancia == null || instancia.isClosed()) {
        instancia = new ListaCompras();
    }
    return instancia;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        BTRefrescar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(190, 147, 234));

        jPanel2.setBackground(new java.awt.Color(190, 147, 234));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        jButton1.setText("generar compras propuestas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BTRefrescar.setText("Refescar");
        BTRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTRefrescarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(397, Short.MAX_VALUE)
                .addComponent(BTRefrescar)
                .addGap(46, 46, 46)
                .addComponent(jButton1)
                .addGap(69, 69, 69))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(BTRefrescar))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(162, 93, 234));
        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(121, 121, 121))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        compraDetalles=comprasManager.obtenerProductosDeVentasPendientes();
        if(!compraDetalles.isEmpty()){
            try {
                comprasPropuestas=comprasManager.generarComprasPropuestas(compraDetalles, Menu.getEmpleado());
                cargarCompras(comprasPropuestas, true);
                existenRegistros=false;
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "No se pudo cargar las Compras propuestas");
            }
        }else{
            JOptionPane.showMessageDialog(null, "No hay ventas nuepvas para sugerir compras");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BTRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTRefrescarActionPerformed
        try {
            cargarCompras(comprasManager.listar(), false);
            existenRegistros=true;
        } catch (Exception ex) {
            
            JOptionPane.showMessageDialog(null, "No se pudo cargar las Compras");
        }
    }//GEN-LAST:event_BTRefrescarActionPerformed
    
    
    public void cargarCompras(ArrayList<Compra> listaCompras, boolean sugerencia) {
        if(!existenRegistros){
           contenedorCompras.removeAll(); 
        }
        

        for (Compra compra : listaCompras) {
            ArrayList<CompraDetalles> cds=new ArrayList<>();
            if(sugerencia){
                for (CompraDetalles compraDetalle : this.compraDetalles) {
                    if(compra.getProveedor().getId()==compraDetalle.getProducto().getProveedor().getId());
                    {
                        cds.add(compraDetalle);
                    }
                }
            }else{
                try {
                    cds=comprasManager.obtenerDetalles(compra.getId());
                } catch (Exception ex) {
                    System.out.println("error: "+ ex.getMessage());
                    JOptionPane.showMessageDialog(null, "No se pudo cargar los detalles de las Compras");
                }
            }
            
            CompraPropuesta propuesto = new CompraPropuesta(cds,compra);
            propuesto.CargarDatos(); 
            contenedorCompras.add(propuesto); 
        }

        contenedorCompras.revalidate();
        contenedorCompras.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTRefrescar;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
