/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

/**
 *
 * @author jheff
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btRegistroProveedores = new javax.swing.JButton();
        btRegistroCliente = new javax.swing.JButton();
        btRegistroProducto = new javax.swing.JButton();
        btAdministrarEmpleado = new javax.swing.JButton();
        btGestionarPedido = new javax.swing.JButton();
        jpPanelMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel4.setBackground(new java.awt.Color(153, 102, 255));

        jLabel1.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Importaciones Lady");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btRegistroProveedores.setBackground(new java.awt.Color(135, 130, 255));
        btRegistroProveedores.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btRegistroProveedores.setForeground(new java.awt.Color(255, 255, 255));
        btRegistroProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/group_10613633.png"))); // NOI18N
        btRegistroProveedores.setText("Registro de proveedores");
        btRegistroProveedores.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btRegistroProveedores.setBorderPainted(false);
        btRegistroProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btRegistroProveedores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btRegistroProveedores.setMargin(new java.awt.Insets(12, 14, 3, 14));
        btRegistroProveedores.setPreferredSize(new java.awt.Dimension(75, 35));
        btRegistroProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistroProveedoresActionPerformed(evt);
            }
        });

        btRegistroCliente.setBackground(new java.awt.Color(135, 130, 255));
        btRegistroCliente.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btRegistroCliente.setForeground(new java.awt.Color(255, 255, 255));
        btRegistroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/group_10613635 (1).png"))); // NOI18N
        btRegistroCliente.setText("Registro Cliente");
        btRegistroCliente.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btRegistroCliente.setBorderPainted(false);
        btRegistroCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btRegistroCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btRegistroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistroClienteActionPerformed(evt);
            }
        });

        btRegistroProducto.setBackground(new java.awt.Color(135, 130, 255));
        btRegistroProducto.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btRegistroProducto.setForeground(new java.awt.Color(255, 255, 255));
        btRegistroProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit_10613619.png"))); // NOI18N
        btRegistroProducto.setText("Registro de productos");
        btRegistroProducto.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btRegistroProducto.setBorderPainted(false);
        btRegistroProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btRegistroProducto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btRegistroProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistroProductoActionPerformed(evt);
            }
        });

        btAdministrarEmpleado.setBackground(new java.awt.Color(135, 130, 255));
        btAdministrarEmpleado.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btAdministrarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        btAdministrarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder_12067190.png"))); // NOI18N
        btAdministrarEmpleado.setText("Administrar Empleados");
        btAdministrarEmpleado.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btAdministrarEmpleado.setBorderPainted(false);
        btAdministrarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAdministrarEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btAdministrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdministrarEmpleadoActionPerformed(evt);
            }
        });

        btGestionarPedido.setBackground(new java.awt.Color(135, 130, 255));
        btGestionarPedido.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btGestionarPedido.setForeground(new java.awt.Color(255, 255, 255));
        btGestionarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clipboard-list_12066966 (1).png"))); // NOI18N
        btGestionarPedido.setText("Gestion de pedido");
        btGestionarPedido.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btGestionarPedido.setBorderPainted(false);
        btGestionarPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btGestionarPedido.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
            .addComponent(btRegistroProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btRegistroProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btRegistroCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btAdministrarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btGestionarPedido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btRegistroProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRegistroProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btRegistroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btAdministrarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btGestionarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpPanelMain.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jpPanelMainLayout = new javax.swing.GroupLayout(jpPanelMain);
        jpPanelMain.setLayout(jpPanelMainLayout);
        jpPanelMainLayout.setHorizontalGroup(
            jpPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 841, Short.MAX_VALUE)
        );
        jpPanelMainLayout.setVerticalGroup(
            jpPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jpPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpPanelMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRegistroProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistroProveedoresActionPerformed
  GestionProveedor proveedor =new GestionProveedor();
        jpPanelMain.add(proveedor);
        proveedor.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btRegistroProveedoresActionPerformed

    private void btRegistroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistroClienteActionPerformed
       GestionClientes cliente =new GestionClientes();
        jpPanelMain.add(cliente);
        cliente.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_btRegistroClienteActionPerformed

    private void btRegistroProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistroProductoActionPerformed
GestionProducto ventanaProducto =new GestionProducto();
        jpPanelMain.add(ventanaProducto);
        ventanaProducto.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btRegistroProductoActionPerformed

    private void btAdministrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdministrarEmpleadoActionPerformed
    DatosEmpleado empleado =new DatosEmpleado();
        jpPanelMain.add(empleado);
        empleado.setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_btAdministrarEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdministrarEmpleado;
    private javax.swing.JButton btGestionarPedido;
    private javax.swing.JButton btRegistroCliente;
    private javax.swing.JButton btRegistroProducto;
    private javax.swing.JButton btRegistroProveedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jpPanelMain;
    // End of variables declaration//GEN-END:variables

    
}
