/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package Presentacion;
import Entidades.Cliente;
import Entidades.Compra;
import Entidades.CompraDetalles;
import Entidades.Empleado;
import Entidades.Producto;
import Entidades.Proveedor;
import Presentacion.Clientes.*;
import Presentacion.Compras.*;
import Presentacion.Productos.*;
import Presentacion.Proveedores.*;
import Presentacion.Ventas.*;
import Presentacion.Empleados.*;
import java.util.ArrayList;
/**
 *
 * @author Amir Altamirano
 */
public class Principal extends javax.swing.JFrame {
    private static Principal menu;
    private static Empleado empleado=new Empleado();
    /**
     * Creates new form Principal
     */
    public Principal(Empleado empleado1) {
        initComponents();
        this.empleado=empleado1;
        menu=this;
        
    }
    
    
    public static Empleado getEmpleado(){
         return empleado;
    }
    
    public static  Principal getInstance(){
        if(menu==null ){
            menu=new Principal(empleado);
        }
        
        return menu;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        RegistrarVentas = new javax.swing.JMenuItem();
        ListaVentasEnCurso = new javax.swing.JMenuItem();
        ListaVentasCompletas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        RegistrarCompras = new javax.swing.JMenuItem();
        ListaComprasEnProgreso = new javax.swing.JMenuItem();
        ListaComprasCompletas = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        RegistrarClinetes = new javax.swing.JMenuItem();
        ListaClientes = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        RegistrarProveedores = new javax.swing.JMenuItem();
        ListaProveedores = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        RegistrarProductos = new javax.swing.JMenuItem();
        ListaProductos = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        MisDatos = new javax.swing.JMenuItem();
        RegistrarEmpleados = new javax.swing.JMenuItem();
        ListaEmpleado = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        Reportes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Importadora Lady");
        getContentPane().setLayout(new java.awt.BorderLayout(963, 599));
        getContentPane().add(desktopPane, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Ventas");

        RegistrarVentas.setText("Registrar venta");
        RegistrarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarVentasActionPerformed(evt);
            }
        });
        jMenu1.add(RegistrarVentas);

        ListaVentasEnCurso.setText("Ventas en curso");
        ListaVentasEnCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaVentasEnCursoActionPerformed(evt);
            }
        });
        jMenu1.add(ListaVentasEnCurso);

        ListaVentasCompletas.setText("Ventas completadas");
        ListaVentasCompletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaVentasCompletasActionPerformed(evt);
            }
        });
        jMenu1.add(ListaVentasCompletas);

        menuBar.add(jMenu1);

        jMenu2.setText("Compras");

        RegistrarCompras.setText("Registrar Compra");
        RegistrarCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarComprasActionPerformed(evt);
            }
        });
        jMenu2.add(RegistrarCompras);

        ListaComprasEnProgreso.setText("Conpras en progreso");
        ListaComprasEnProgreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaComprasEnProgresoActionPerformed(evt);
            }
        });
        jMenu2.add(ListaComprasEnProgreso);

        ListaComprasCompletas.setText("Compras completas");
        ListaComprasCompletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaComprasCompletasActionPerformed(evt);
            }
        });
        jMenu2.add(ListaComprasCompletas);

        menuBar.add(jMenu2);

        jMenu3.setText("Clientes");

        RegistrarClinetes.setText("Registrar Cliente");
        RegistrarClinetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarClinetesActionPerformed(evt);
            }
        });
        jMenu3.add(RegistrarClinetes);

        ListaClientes.setText("Lista de Clientes");
        ListaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaClientesActionPerformed(evt);
            }
        });
        jMenu3.add(ListaClientes);

        menuBar.add(jMenu3);

        jMenu4.setText("Proveedor");

        RegistrarProveedores.setText("Registrar proveedor");
        RegistrarProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarProveedoresActionPerformed(evt);
            }
        });
        jMenu4.add(RegistrarProveedores);

        ListaProveedores.setText("Lista de Proveedores");
        ListaProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaProveedoresActionPerformed(evt);
            }
        });
        jMenu4.add(ListaProveedores);

        menuBar.add(jMenu4);

        jMenu5.setText("Productos");
        jMenu5.setToolTipText("");

        RegistrarProductos.setText("Registrar Productos");
        RegistrarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarProductosActionPerformed(evt);
            }
        });
        jMenu5.add(RegistrarProductos);

        ListaProductos.setText("Lista de Productos");
        ListaProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaProductosActionPerformed(evt);
            }
        });
        jMenu5.add(ListaProductos);

        menuBar.add(jMenu5);

        jMenu6.setText("Empleados");

        MisDatos.setText("YO");
        MisDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MisDatosActionPerformed(evt);
            }
        });
        jMenu6.add(MisDatos);

        RegistrarEmpleados.setText("Registrar Empleado");
        RegistrarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarEmpleadosActionPerformed(evt);
            }
        });
        jMenu6.add(RegistrarEmpleados);

        ListaEmpleado.setText("Lista de empleados");
        ListaEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaEmpleadoActionPerformed(evt);
            }
        });
        jMenu6.add(ListaEmpleado);

        menuBar.add(jMenu6);

        jMenu7.setText("Reportes");

        Reportes.setText("Reportes");
        Reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportesActionPerformed(evt);
            }
        });
        jMenu7.add(Reportes);

        menuBar.add(jMenu7);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarVentasActionPerformed
        RegistrarVenta ventana =RegistrarVenta.getR_ventas();
        desktopPane.add(ventana);
        ventana.setVisible(true);
    }//GEN-LAST:event_RegistrarVentasActionPerformed

    private void ListaProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaProveedoresActionPerformed
        GestionProveedor ventanaGestionProveedor=GestionProveedor.getProveedor();
        desktopPane.add(ventanaGestionProveedor);
        ventanaGestionProveedor.setVisible(true);
    }//GEN-LAST:event_ListaProveedoresActionPerformed

    private void ListaVentasEnCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaVentasEnCursoActionPerformed
        ListaVentas ventanaListaVentas=ListaVentas.getVentanaListaVentas();
        desktopPane.add(ventanaListaVentas);
        ventanaListaVentas.setVisible(true);
    }//GEN-LAST:event_ListaVentasEnCursoActionPerformed

    private void RegistrarComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarComprasActionPerformed
        EditarCompra ventanaEditarCompra=new EditarCompra(null, null);
        desktopPane.add(ventanaEditarCompra);
        ventanaEditarCompra.setVisible(true);
    }//GEN-LAST:event_RegistrarComprasActionPerformed

    private void ListaComprasEnProgresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaComprasEnProgresoActionPerformed
        ListaCompras ventanaListaCompras= ListaCompras.getListaCompra();
        desktopPane.add(ventanaListaCompras);
        ventanaListaCompras.setVisible(true);
    }//GEN-LAST:event_ListaComprasEnProgresoActionPerformed

    private void RegistrarClinetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarClinetesActionPerformed
        RegistrarClinete(false, null);
    }//GEN-LAST:event_RegistrarClinetesActionPerformed

    private void ListaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaClientesActionPerformed
        GestionClientes ventanaGestionClientes= GestionClientes.getCliente();
        desktopPane.add(ventanaGestionClientes);
        ventanaGestionClientes.setVisible(true);
    }//GEN-LAST:event_ListaClientesActionPerformed

    private void RegistrarProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarProveedoresActionPerformed
        RegistrarProveedor(false, null);
    }//GEN-LAST:event_RegistrarProveedoresActionPerformed

    private void RegistrarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarProductosActionPerformed
        RegistrarProducto(false, null);
    }//GEN-LAST:event_RegistrarProductosActionPerformed

    private void ListaProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaProductosActionPerformed
        GestionProducto ventanaGestionProducto=GestionProducto.getProducto();
        desktopPane.add(ventanaGestionProducto);
        ventanaGestionProducto.setVisible(true);
    }//GEN-LAST:event_ListaProductosActionPerformed

    private void MisDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MisDatosActionPerformed
        DatosEmpleado ventanDatosEmpleado=DatosEmpleado.getEmpleados();
        desktopPane.add(ventanDatosEmpleado);
        ventanDatosEmpleado.setVisible(true);
    }//GEN-LAST:event_MisDatosActionPerformed

    private void RegistrarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarEmpleadosActionPerformed
        RegistrarEmpleado ventanaRegistrarEmpleado=RegistrarEmpleado.getInstancia();
        desktopPane.add(ventanaRegistrarEmpleado);
        ventanaRegistrarEmpleado.setVisible(true);
    }//GEN-LAST:event_RegistrarEmpleadosActionPerformed

    private void ListaEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaEmpleadoActionPerformed
        ListaEmpleados ventanaListaEmpleados= ListaEmpleados.getInstancia();
        desktopPane.add(ventanaListaEmpleados);
        ventanaListaEmpleados.setVisible(true);
    }//GEN-LAST:event_ListaEmpleadoActionPerformed

    private void ListaVentasCompletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaVentasCompletasActionPerformed
        VentasCompletas ventanVentasCompletas= VentasCompletas.getIntancia();
        desktopPane.add(ventanVentasCompletas);
        ventanVentasCompletas.setVisible(true);
    }//GEN-LAST:event_ListaVentasCompletasActionPerformed

    private void ReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportesActionPerformed
       Reportes_Lady ventanaReportes_Lady=Reportes_Lady.getReportes();
       desktopPane.add(ventanaReportes_Lady);
       ventanaReportes_Lady.setVisible(true);
    }//GEN-LAST:event_ReportesActionPerformed

    private void ListaComprasCompletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaComprasCompletasActionPerformed
        ComprasCompletas  ventanaComprasCompletas=ComprasCompletas.getInstancia();
        desktopPane.add(ventanaComprasCompletas);
        ventanaComprasCompletas.setVisible(true);
    }//GEN-LAST:event_ListaComprasCompletasActionPerformed

    public void ModificarEmpleado(Empleado e){
        RegistrarEmpleado ventanaRegistrarEmpleado=new RegistrarEmpleado(e);
        desktopPane.add(ventanaRegistrarEmpleado);
        ventanaRegistrarEmpleado.setVisible(true);
    }
    
    public void RegistrarProducto(boolean si, Producto p){
        RegistarProducto ventanaRegistarProducto= RegistarProducto.getIntancia();
        desktopPane.add(ventanaRegistarProducto);
        if(!si && p==null){
            ventanaRegistarProducto.setProdcutoSeleccionado(null);
            ventanaRegistarProducto.setVisible(true);
        }else{

            ventanaRegistarProducto.setProdcutoSeleccionado(p);
            ventanaRegistarProducto.cargarDatosProductoSeleccionado();
            ventanaRegistarProducto.setVisible(true);
        }
    }
    
    public void RegistrarClinete(boolean si, Cliente c){
        RegistrarCliente ventanaRegistrarCliente=RegistrarCliente.getIntancia();
        desktopPane.add(ventanaRegistrarCliente);
        if(!si && c==null){
            ventanaRegistrarCliente.setClienteSelecionado(null);
            ventanaRegistrarCliente.setVisible(true);
        }else{

            ventanaRegistrarCliente.setClienteSelecionado(c);
            ventanaRegistrarCliente.cargarDatosClienteSeleccionado();
            ventanaRegistrarCliente.setVisible(true);
        }
    }
    
    public void RegistrarProveedor(boolean si, Proveedor p){
        RegistrarProveedor ventanaRegistrarProveedor= RegistrarProveedor.getIntancia();
        desktopPane.add(ventanaRegistrarProveedor);
        
        if(!si && p==null){
            ventanaRegistrarProveedor.setProveedorSeleccionado(null);
            ventanaRegistrarProveedor.setVisible(true);
        }else{

            ventanaRegistrarProveedor.setProveedorSeleccionado(p);
            ventanaRegistrarProveedor.cargarDatosProveedorSeleccionado();
            ventanaRegistrarProveedor.setVisible(true);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal(empleado).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ListaClientes;
    private javax.swing.JMenuItem ListaComprasCompletas;
    private javax.swing.JMenuItem ListaComprasEnProgreso;
    private javax.swing.JMenuItem ListaEmpleado;
    private javax.swing.JMenuItem ListaProductos;
    private javax.swing.JMenuItem ListaProveedores;
    private javax.swing.JMenuItem ListaVentasCompletas;
    private javax.swing.JMenuItem ListaVentasEnCurso;
    private javax.swing.JMenuItem MisDatos;
    private javax.swing.JMenuItem RegistrarClinetes;
    private javax.swing.JMenuItem RegistrarCompras;
    private javax.swing.JMenuItem RegistrarEmpleados;
    private javax.swing.JMenuItem RegistrarProductos;
    private javax.swing.JMenuItem RegistrarProveedores;
    private javax.swing.JMenuItem RegistrarVentas;
    private javax.swing.JMenuItem Reportes;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

    
    public void detallesCompras(Compra compra, ArrayList<CompraDetalles>  detalles){
       DettalesDeCompra dettalesDeCompra=new DettalesDeCompra(compra, detalles);
       desktopPane.add(dettalesDeCompra);
       dettalesDeCompra.setVisible(true);
    }
    
    public void EditarCompra(Compra compra, ArrayList<CompraDetalles>  detalles){
        EditarCompra editarCompra=new EditarCompra(detalles, compra);
        desktopPane.add(editarCompra);
        editarCompra.setVisible(true);

    }
    
    public void detallesVenta(int id){

        DetallesDeVenta VentaDetalles = new DetallesDeVenta(id);
        desktopPane.add(VentaDetalles);
        VentaDetalles.setVisible(true);
    
    }
}
