/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Entidades.Empleado;
import Logica.LoginManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/**
 *
 * @author Amir Altamirano
 */
public class RecuperrarContraseña extends javax.swing.JFrame {
    
    private LoginManager lm = new LoginManager();
    private Empleado empleado=new Empleado();
    private int pasoActual = 1;
    private Timer cronometro;
    private int segundosRestantes = 90;
    /**
     * Creates new form RecuperrarContraseña
     */
    public RecuperrarContraseña() {
        initComponents();
        LayeredValidarUsuario.setVisible(true);
        LayeredVerificarCodigo.setVisible(false);
        LayeredCambioContraseña.setVisible(false);
        this.pack(); // Ajusta el tamaño
        this.setLocationRelativeTo(null); // Centra la ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LayeredValidarUsuario = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        TFUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TFNroDocumento = new javax.swing.JTextField();
        LayeredVerificarCodigo = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        TFCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LayeredCambioContraseña = new javax.swing.JLayeredPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PFContraseña = new javax.swing.JPasswordField();
        PFConfirmarContraseña = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        LayeredValidarUsuario.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Usuario");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("N° Documento");

        LayeredValidarUsuario.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredValidarUsuario.setLayer(TFUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredValidarUsuario.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredValidarUsuario.setLayer(TFNroDocumento, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout LayeredValidarUsuarioLayout = new javax.swing.GroupLayout(LayeredValidarUsuario);
        LayeredValidarUsuario.setLayout(LayeredValidarUsuarioLayout);
        LayeredValidarUsuarioLayout.setHorizontalGroup(
            LayeredValidarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayeredValidarUsuarioLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(LayeredValidarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFNroDocumento)
                    .addComponent(TFUsuario)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LayeredValidarUsuarioLayout.setVerticalGroup(
            LayeredValidarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayeredValidarUsuarioLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFNroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        LayeredVerificarCodigo.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Ingrese codigo de veridicacion");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Cronometro");

        jLabel7.setForeground(new java.awt.Color(102, 102, 255));
        jLabel7.setText("volver a enviar codigo");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });

        LayeredVerificarCodigo.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredVerificarCodigo.setLayer(TFCodigo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredVerificarCodigo.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredVerificarCodigo.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout LayeredVerificarCodigoLayout = new javax.swing.GroupLayout(LayeredVerificarCodigo);
        LayeredVerificarCodigo.setLayout(LayeredVerificarCodigoLayout);
        LayeredVerificarCodigoLayout.setHorizontalGroup(
            LayeredVerificarCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayeredVerificarCodigoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(LayeredVerificarCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LayeredVerificarCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addGroup(LayeredVerificarCodigoLayout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addContainerGap(89, Short.MAX_VALUE)))
                    .addGroup(LayeredVerificarCodigoLayout.createSequentialGroup()
                        .addComponent(TFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(185, Short.MAX_VALUE))))
        );
        LayeredVerificarCodigoLayout.setVerticalGroup(
            LayeredVerificarCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayeredVerificarCodigoLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGroup(LayeredVerificarCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LayeredVerificarCodigoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel4))
                    .addGroup(LayeredVerificarCodigoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        LayeredCambioContraseña.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nueva contraseña");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Confirmar Contraseña");

        LayeredCambioContraseña.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredCambioContraseña.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredCambioContraseña.setLayer(PFContraseña, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredCambioContraseña.setLayer(PFConfirmarContraseña, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout LayeredCambioContraseñaLayout = new javax.swing.GroupLayout(LayeredCambioContraseña);
        LayeredCambioContraseña.setLayout(LayeredCambioContraseñaLayout);
        LayeredCambioContraseñaLayout.setHorizontalGroup(
            LayeredCambioContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayeredCambioContraseñaLayout.createSequentialGroup()
                .addGroup(LayeredCambioContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(LayeredCambioContraseñaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LayeredCambioContraseñaLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(LayeredCambioContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PFContraseña)
                            .addComponent(PFConfirmarContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        LayeredCambioContraseñaLayout.setVerticalGroup(
            LayeredCambioContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayeredCambioContraseñaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PFContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PFConfirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LayeredVerificarCodigo)
                    .addComponent(LayeredValidarUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LayeredCambioContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(92, 92, 92))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LayeredValidarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LayeredCambioContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LayeredVerificarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        switch (pasoActual) {
            case 1:
                // Mostrar siguiente paso: Verificar código
                
                if(TFNroDocumento.getText()!="" && TFUsuario.getText()!=""){
                    empleado=lm.buscarEmpleado(TFUsuario.getText(), TFNroDocumento.getText());
                    
                }else{
                    return;
                }
                if(empleado!=null){
                    lm.enviarCodigo(empleado.getCorreo());
                    pasoActual = 2;
                    iniciarCronometro();
                    LayeredValidarUsuario.setVisible(false);
                    LayeredVerificarCodigo.setVisible(true);
                    LayeredCambioContraseña.setVisible(false);
                }
                
                
                break;

            case 2:
                // Mostrar último paso: Cambio de contraseña
                
                if(lm.codigo.equals(TFCodigo.getText())){
                    pasoActual = 3;
                    jButton1.setText("Finalizar");  
                    LayeredValidarUsuario.setVisible(false);
                    LayeredVerificarCodigo.setVisible(false);
                    LayeredCambioContraseña.setVisible(true);
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Codigo einvalido.");
                }
                
                break;

            case 3:
                String pass1 = new String(PFContraseña.getPassword());
                String pass2 = new String(PFConfirmarContraseña.getPassword());

                if (pass1.equals(pass2)) {
                    try {
                        lm.CambiarContraseña(empleado, pass1);  // Método que llama a BDEmpleado.cambiarContraseña()
                        JOptionPane.showMessageDialog(null, "La contraseña se cambió correctamente.");

                        this.dispose(); // Cierra la ventana actual
                        SwingUtilities.invokeLater(() -> new Login().setVisible(true)); // Vuelve al login
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, "Error al cambiar la contraseña: " + ex.getMessage());
                        ex.printStackTrace();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden.");
                }
                // Aquí podrías guardar la nueva contraseña o cerrar la ventana
                // JOptionPane.showMessageDialog(this, "Contraseña cambiada correctamente.");
                 // Cierra la ventana
                break;
        }
        this.pack(); // Ajusta el tamaño
        this.setLocationRelativeTo(null); // Centra la ventana
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        lm.enviarCodigo(empleado.getCorreo());
    }//GEN-LAST:event_jLabel7MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecuperrarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecuperrarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecuperrarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecuperrarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecuperrarContraseña().setVisible(true);
            }
        });
    }
    
    private void iniciarCronometro() {
        segundosRestantes = 60;
        jLabel4.setText("01:00");

        cronometro = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                segundosRestantes--;

                // Formatear minutos y segundos
                int minutos = segundosRestantes / 60;
                int segundos = segundosRestantes % 60;
                String tiempo = String.format("%02d:%02d", minutos, segundos);
                jLabel4.setText(tiempo);

                if (segundosRestantes <= 0) {
                    cronometro.stop();
                    // Acción cuando termina el cronómetro
                    jLabel4.setText("¡Tiempo agotado!");
                    TFCodigo.setEnabled(false); // Bloquea el ingreso del código
                    
                    lm.codigo="";
                    if(pasoActual==2){
                        jButton1.setEnabled(false); // Desactiva el botón "Siguiente"
                        JOptionPane.showMessageDialog(null, "El tiempo ha expirado. Vuelva a solicitar el código.");
                    }
                    
                }
            }
        });

        cronometro.start();
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane LayeredCambioContraseña;
    private javax.swing.JLayeredPane LayeredValidarUsuario;
    private javax.swing.JLayeredPane LayeredVerificarCodigo;
    private javax.swing.JPasswordField PFConfirmarContraseña;
    private javax.swing.JPasswordField PFContraseña;
    private javax.swing.JTextField TFCodigo;
    private javax.swing.JTextField TFNroDocumento;
    private javax.swing.JTextField TFUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
