/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion.Empleados;

import AccesoDatos.BDTipo_Documento;
import Entidades.Cargo;
import Entidades.Empleado;
import Entidades.Tipo_documento;
import Logica.EmpleadoManager;
import Logica.LoginManager;
import Presentacion.Modelos.ModeloComboboxCargo;
import Presentacion.Modelos.ModeloComboboxTipoDocumento;
import java.awt.Image;
import java.awt.datatransfer.DataFlavor;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.TransferHandler;

/**
 *
 * @author Amir Altamirano
 */
public class RegistrarEmpleado extends javax.swing.JInternalFrame {
    private static RegistrarEmpleado instancia;
    
    private EmpleadoManager manager=new EmpleadoManager();
    private BDTipo_Documento bdtd = new BDTipo_Documento();
    private ModeloComboboxTipoDocumento modeloComboboxTipoDocumento=new ModeloComboboxTipoDocumento();
    private ModeloComboboxCargo comboboxCargo=new ModeloComboboxCargo();
    private LoginManager lm = new LoginManager();
    
    private Empleado empleadoEditar = null;
    /**
     * Creates new form RegistrarEmpleado
     */
    public RegistrarEmpleado() {
        initComponents();
        LBImagenEmpleado.setTransferHandler(new TransferHandler() {
            @Override
            public boolean canImport(TransferHandler.TransferSupport support) {
                return support.isDataFlavorSupported(DataFlavor.javaFileListFlavor);
            }

            @Override
            public boolean importData(TransferHandler.TransferSupport support) {
                try {
                    List<File> archivos = (List<File>) support.getTransferable().getTransferData(DataFlavor.javaFileListFlavor);
                    File archivo = archivos.get(0);
                    BufferedImage imagen = ImageIO.read(archivo);

                    if (imagen == null) {
                        JOptionPane.showMessageDialog(null, "Archivo no es una imagen válida.");
                        return false;
                    }
                    String nombre = archivo.getName().toLowerCase();
                    if (!(nombre.endsWith(".png") || nombre.endsWith(".jpg") || nombre.endsWith(".jpeg") || nombre.endsWith(".bmp"))) {
                        JOptionPane.showMessageDialog(null, "Solo se permiten imágenes PNG, JPG, BMP.");
                        return false;
                    }

                    // Redimensionar imagen
                    Image escalada = imagen.getScaledInstance(LBImagenEmpleado.getWidth(), LBImagenEmpleado.getHeight(), Image.SCALE_SMOOTH);
                    LBImagenEmpleado.setIcon(new ImageIcon(escalada));
                    LBImagenEmpleado.setText("");

                    return true;
                } catch (Exception ex) {
                    ex.printStackTrace();
                    return false;
                }
            }
        });
        
        CragarComboBox();
    }
    
    public RegistrarEmpleado(Empleado empleado) {
        this(); // Llama al constructor por defecto
        this.empleadoEditar = empleado;
        cargarDatosEmpleado(empleado);
        TFUsuario.setEnabled(false); // Desactivar edición de usuario
        PFContraseña.setEnabled(false); // Desactivar contraseña
        PFVerificarContraseña.setEnabled(false);
        jButton1.setText("Modificar");
    }
    
    
    public static RegistrarEmpleado getInstancia(){
        if(instancia==null || instancia.isClosed()){
            instancia=new RegistrarEmpleado();
        }
        return instancia;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Generos = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        LBImagenEmpleado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TFNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TFNroDocumento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CBTipoDocumento = new javax.swing.JComboBox<>();
        rbMasculino = new javax.swing.JRadioButton();
        rbFemenino = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        TFDIreccion = new javax.swing.JTextField();
        TFTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TFCorreo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        CBCrago = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TFUsuario = new javax.swing.JTextField();
        PFContraseña = new javax.swing.JPasswordField();
        PFVerificarContraseña = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        LBImagenEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LBImagenEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBImagenEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png"))); // NOI18N
        LBImagenEmpleado.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        LBImagenEmpleado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("N° de documento:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Tipo de documento");

        CBTipoDocumento.setModel(this.modeloComboboxTipoDocumento);

        Generos.add(rbMasculino);
        rbMasculino.setForeground(new java.awt.Color(0, 0, 0));
        rbMasculino.setText("Maculino");

        Generos.add(rbFemenino);
        rbFemenino.setForeground(new java.awt.Color(0, 0, 0));
        rbFemenino.setText("Femenino");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Genero");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Fecha de Nacimineto:");

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Direccion:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Telefono: ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Correo:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Cargo:");

        CBCrago.setModel(this.comboboxCargo);
        CBCrago.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TFDIreccion, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(CBCrago, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TFDIreccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CBCrago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Usuario");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Contraseña");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Confirmar Contraseña");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PFVerificarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel12)
                            .addGap(18, 18, 18)
                            .addComponent(PFContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGap(95, 95, 95)
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(TFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(TFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(PFContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(PFVerificarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(LBImagenEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(17, 17, 17)
                                .addComponent(TFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CBTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TFNroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jLabel5)
                                .addGap(31, 31, 31)
                                .addComponent(rbMasculino)
                                .addGap(32, 32, 32)
                                .addComponent(rbFemenino)))
                        .addGap(50, 50, 50))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(41, 41, 41))))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(CBTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TFNroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(rbMasculino)
                            .addComponent(rbFemenino)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LBImagenEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        java.sql.Date fechaSQL=null;
        System.out.println("inde de cargo: "+ CBCrago.getSelectedIndex());
        System.out.println("inde de tipo: "+ CBTipoDocumento.getSelectedIndex());
        if (jDateChooser1.getDate() != null) {
            fechaSQL = new java.sql.Date(jDateChooser1.getDate().getTime());
            // úsalo como quieras
        }
        boolean datosValidos = manager.validarTodo(
        TFNombre.getText(),
        fechaSQL,
        TFNroDocumento.getText(),
        (rbMasculino.isSelected() ? 'M' : rbFemenino.isSelected() ? 'F' : ' '),
        TFTelefono.getText(),
        TFDIreccion.getText(),
        TFCorreo.getText(),
        TFUsuario.getText(),
        new String(PFContraseña.getPassword()),
        new String(PFVerificarContraseña.getPassword()),
        CBTipoDocumento.getSelectedIndex(),
        CBCrago.getSelectedIndex()
    );

    if (datosValidos) {
        String rutaImagenEmpleado="";
        BufferedImage img = obtenerImagenDeLabel();
            if (img != null) {
                // Opcional: podrías querer borrar la imagen anterior antes de guardar la nueva
                rutaImagenEmpleado=manager.guardarImagen(img);
            }
        Tipo_documento tipoDocumento = modeloComboboxTipoDocumento.getSeleccionado();
        Cargo cargo = comboboxCargo.getSeleccionado();
        char genero = rbMasculino.isSelected() ? 'M' : rbFemenino.isSelected() ? 'F' : ' ';

            
         if (empleadoEditar == null) {
            try {
                manager.crearEmpleadoDesdeFormulario(
                        TFNombre.getText(),
                        TFUsuario.getText(),
                        tipoDocumento,
                        TFNroDocumento.getText(),
                        fechaSQL,
                        genero,
                        new String(PFContraseña.getPassword()),
                        cargo,
                        TFDIreccion.getText(),
                        TFTelefono.getText(),
                        TFCorreo.getText(),
                        rutaImagenEmpleado // asegúrate que esta variable contiene el path
                );  
                limpiarFormulario();
            
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Hubo problemas al crear a empleado: " + e.getMessage(), "Error con la base de datos", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            try {
                // Modificación
                manager.actualizarEmpleadoDesdeFormulario(
                        empleadoEditar.getId(), // Usamos el ID del empleado
                        TFNombre.getText(),
                        tipoDocumento,
                        TFNroDocumento.getText(),
                        fechaSQL,
                        genero,
                        cargo,
                        TFDIreccion.getText(),
                        TFTelefono.getText(),
                        TFCorreo.getText(),
                        rutaImagenEmpleado
                );
            } catch (Exception ex) {
                 JOptionPane.showMessageDialog(null, "Hubo problemas al modificar empleado a empleado: " + ex.getMessage(), "Error con la base de datos", JOptionPane.ERROR_MESSAGE);
            }
        }
        limpiarFormulario();
        
    }

    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    public BufferedImage obtenerImagenDeLabel() {
        if (LBImagenEmpleado.getIcon() != null && LBImagenEmpleado.getIcon() instanceof ImageIcon) {
            Image imagen = ((ImageIcon) LBImagenEmpleado.getIcon()).getImage();

            // Crear un BufferedImage compatible con la imagen
            BufferedImage buffered = new BufferedImage(
                    imagen.getWidth(null),
                    imagen.getHeight(null),
                    BufferedImage.TYPE_INT_ARGB // Puedes usar TYPE_INT_RGB si no necesitas transparencia
            );

            // Dibujar la imagen en el BufferedImage
            buffered.getGraphics().drawImage(imagen, 0, 0, null);
            return buffered;
        }
        return null; // No hay imagen en el label
    }
    
    private void cargarDatosEmpleado(Empleado emp) {
        TFNombre.setText(emp.getNombre());
        TFNroDocumento.setText(emp.getNroDocumento());
        jDateChooser1.setDate(emp.getFechaNacimiento());

        // Seleccionar el tipo de documento
        int indexTipoDoc = modeloComboboxTipoDocumento.getSelectTipoDocumento(emp.getTipoDocumento());
        CBTipoDocumento.setSelectedIndex(indexTipoDoc);

        // Seleccionar el cargo
        int indexCargo = comboboxCargo.getSelectCargo(emp.getCargo());
        CBCrago.setSelectedIndex(indexCargo);

        if (emp.getGenero() == 'M') {
            rbMasculino.setSelected(true);
        } else if (emp.getGenero() == 'F') {
            rbFemenino.setSelected(true);
        }

        TFDIreccion.setText(emp.getDireccion());
        TFTelefono.setText(emp.getTelefono());
        TFCorreo.setText(emp.getCorreo());
        TFUsuario.setText(emp.getUsuario());

        // Imagen
        if (emp.getUrl() != null && !emp.getUrl().isEmpty()) {
            File archivo = new File(emp.getUrl());
            if (archivo.exists()) {
                try {
                    BufferedImage imagen = ImageIO.read(archivo);
                    Image escalada = imagen.getScaledInstance(LBImagenEmpleado.getWidth(), LBImagenEmpleado.getHeight(), Image.SCALE_SMOOTH);
                    LBImagenEmpleado.setIcon(new ImageIcon(escalada));
                    LBImagenEmpleado.setText("");
                } catch (Exception e) {
                    System.err.println("Error al cargar imagen del empleado: " + e.getMessage());
                }
            }
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBCrago;
    private javax.swing.JComboBox<String> CBTipoDocumento;
    private javax.swing.ButtonGroup Generos;
    private javax.swing.JLabel LBImagenEmpleado;
    private javax.swing.JPasswordField PFContraseña;
    private javax.swing.JPasswordField PFVerificarContraseña;
    private javax.swing.JTextField TFCorreo;
    private javax.swing.JTextField TFDIreccion;
    private javax.swing.JTextField TFNombre;
    private javax.swing.JTextField TFNroDocumento;
    private javax.swing.JTextField TFTelefono;
    private javax.swing.JTextField TFUsuario;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton rbFemenino;
    private javax.swing.JRadioButton rbMasculino;
    // End of variables declaration//GEN-END:variables
    
    private void limpiarFormulario() {
        TFNombre.setText("");
        TFUsuario.setText("");
        TFNroDocumento.setText("");
        jDateChooser1.setDate(null);
        rbMasculino.setSelected(false);
        rbFemenino.setSelected(false);
        PFContraseña.setText("");
        PFVerificarContraseña.setText("");
        TFDIreccion.setText("");
        TFTelefono.setText("");
        TFCorreo.setText("");
        CBTipoDocumento.setSelectedIndex(0);
        CBCrago.setSelectedIndex(0);
        LBImagenEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png")));
        // limpiar imagen si es necesario
    }
    
    public void CragarComboBox(){
        
        try {
            comboboxCargo.setListadoCargo(lm.cargarCargos());
            modeloComboboxTipoDocumento.setListadoTipoDocumento(bdtd.listar());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "no se puedo cargar los cargos y tipo de documento", "Error con la base de datos", JOptionPane.ERROR_MESSAGE);
        }
    }
    
}
