/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion.Productos;

import Entidades.Producto;
import Entidades.Proveedor;
import Logica.ProductoManager;
import Logica.ProveeedorManager;
import Presentacion.Modelos.ModeloComboboxProveedores;
import java.awt.Color;
import java.awt.Image;
import java.awt.datatransfer.DataFlavor;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.TransferHandler;

/**
 *
 * @author Amir Altamirano
 */
public class RegistarProducto extends javax.swing.JInternalFrame {
    private static RegistarProducto instancia;
    private ProductoManager pm;
    private ProveeedorManager proveeedorManager;
    private ModeloComboboxProveedores comboboxProveedor = new ModeloComboboxProveedores();
    private Producto productoSeleccionado = null;
    /**
     * Creates new form RegistarProducto
     */
    public RegistarProducto() {
        initComponents();
        
        pm = new ProductoManager();
        proveeedorManager = new ProveeedorManager();

        /*FUNCION DE GUARDADO DE IMAGEN*/
        lblImagen.setHorizontalAlignment(SwingConstants.CENTER);
        lblImagen.setText("Arrastra aquí una imagen");
        lblImagen.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        lblImagen.setTransferHandler(new TransferHandler() {
            @Override
            public boolean canImport(TransferHandler.TransferSupport support) {
                return support.isDataFlavorSupported(DataFlavor.javaFileListFlavor);
            }

            @Override
            public boolean importData(TransferHandler.TransferSupport support) {
                try {
                    List<File> archivos = (List<File>) support.getTransferable().getTransferData(DataFlavor.javaFileListFlavor);
                    File archivo = archivos.get(0);
                    BufferedImage imagen = ImageIO.read(archivo);

                    if (imagen == null) {
                        JOptionPane.showMessageDialog(null, "Archivo no es una imagen válida.");
                        return false;
                    }
                    String nombre = archivo.getName().toLowerCase();
                    if (!(nombre.endsWith(".png") || nombre.endsWith(".jpg") || nombre.endsWith(".jpeg") || nombre.endsWith(".bmp"))) {
                        JOptionPane.showMessageDialog(null, "Solo se permiten imágenes PNG, JPG, BMP.");
                        return false;
                    }

                    // Redimensionar imagen
                    Image escalada = imagen.getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_SMOOTH);
                    lblImagen.setIcon(new ImageIcon(escalada));
                    lblImagen.setText("");

                    return true;
                } catch (Exception ex) {
                    ex.printStackTrace();
                    return false;
                }
            }
        });
        
        CargarCombobox();
    }
    
    public void setProdcutoSeleccionado(Producto p){
        this.productoSeleccionado= p;
    }
    
    public static RegistarProducto getIntancia(){
        if(instancia==null || instancia.isClosed()){
            instancia=new RegistarProducto();
        }
        return instancia;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LayeredRegistro_producto = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        TFNombre = new javax.swing.JTextField();
        lblImagen = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SPPrecioCompra = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        SPPrecioVenta = new javax.swing.JSpinner();
        Registrar = new javax.swing.JButton();
        CBProveedores = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        SPStock = new javax.swing.JSpinner();

        setBackground(new java.awt.Color(204, 204, 255));
        setClosable(true);

        LayeredRegistro_producto.setBackground(new java.awt.Color(204, 204, 255));
        LayeredRegistro_producto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("Nombre:");

        TFNombre.setBackground(new java.awt.Color(204, 204, 255));
        TFNombre.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        TFNombre.setForeground(new java.awt.Color(255, 255, 255));
        TFNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        lblImagen.setBackground(new java.awt.Color(255, 255, 255));
        lblImagen.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add_16750539.png"))); // NOI18N
        lblImagen.setToolTipText("");
        lblImagen.setBorder(new javax.swing.border.MatteBorder(null));
        lblImagen.setRequestFocusEnabled(false);
        lblImagen.setVerifyInputWhenFocusTarget(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("Precion Compra:");
        jLabel3.setToolTipText("");

        SPPrecioCompra.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 0.5f));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("Precio Venta:");

        SPPrecioVenta.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 0.5f));

        Registrar.setBackground(new java.awt.Color(153, 153, 255));
        Registrar.setText("Registrar");
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });

        CBProveedores.setModel(this.comboboxProveedor);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setText("Proveedor");
        jLabel5.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("Stock:");
        jLabel6.setToolTipText("");

        SPStock.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        LayeredRegistro_producto.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredRegistro_producto.setLayer(TFNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredRegistro_producto.setLayer(lblImagen, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredRegistro_producto.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredRegistro_producto.setLayer(SPPrecioCompra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredRegistro_producto.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredRegistro_producto.setLayer(SPPrecioVenta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredRegistro_producto.setLayer(Registrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredRegistro_producto.setLayer(CBProveedores, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredRegistro_producto.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredRegistro_producto.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredRegistro_producto.setLayer(SPStock, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout LayeredRegistro_productoLayout = new javax.swing.GroupLayout(LayeredRegistro_producto);
        LayeredRegistro_producto.setLayout(LayeredRegistro_productoLayout);
        LayeredRegistro_productoLayout.setHorizontalGroup(
            LayeredRegistro_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayeredRegistro_productoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(LayeredRegistro_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LayeredRegistro_productoLayout.createSequentialGroup()
                        .addComponent(Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(LayeredRegistro_productoLayout.createSequentialGroup()
                        .addGroup(LayeredRegistro_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LayeredRegistro_productoLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LayeredRegistro_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(LayeredRegistro_productoLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(27, 27, 27)
                                    .addComponent(SPStock, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(LayeredRegistro_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(LayeredRegistro_productoLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CBProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LayeredRegistro_productoLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(SPPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LayeredRegistro_productoLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(SPPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 63, Short.MAX_VALUE))))
        );
        LayeredRegistro_productoLayout.setVerticalGroup(
            LayeredRegistro_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayeredRegistro_productoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(LayeredRegistro_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(LayeredRegistro_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(SPPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(LayeredRegistro_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SPPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LayeredRegistro_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(SPStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LayeredRegistro_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CBProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(LayeredRegistro_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(17, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 567, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(LayeredRegistro_producto)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
        // --- Validación de campos ---
        if (TFNombre.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre del producto no puede estar vacío.", "Campo Requerido", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (productoSeleccionado == null) {
            // --- MODO REGISTRO ---
            Producto nuevoProducto = new Producto();
            nuevoProducto.setNombre(TFNombre.getText().trim());
            nuevoProducto.setPrecioCompra((float) SPPrecioCompra.getValue());
            nuevoProducto.setPrecioVenta((float) SPPrecioVenta.getValue());
            nuevoProducto.setProveedor(comboboxProveedor.getSeleccionado());
            nuevoProducto.setStock((int) SPStock.getValue());

            BufferedImage img = obtenerImagenDeLabel();
            if (img != null) {
                nuevoProducto.setUrl(pm.guardarImagen(img));
            }

            if (pm.registrarProducto(nuevoProducto)) {
                JOptionPane.showMessageDialog(this, "Producto registrado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                //cargarTabla();
                limpiarFormulario();

            } else {
                JOptionPane.showMessageDialog(this, "No se pudo registrar el producto.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            // --- MODO ACTUALIZACIÓN ---
            productoSeleccionado.setNombre(TFNombre.getText().trim());
            productoSeleccionado.setPrecioCompra((float) SPPrecioCompra.getValue());
            productoSeleccionado.setPrecioVenta((float) SPPrecioVenta.getValue());
            productoSeleccionado.setProveedor(comboboxProveedor.getSeleccionado());

            BufferedImage img = obtenerImagenDeLabel();
            if (img != null) {
                // Opcional: podrías querer borrar la imagen anterior antes de guardar la nueva
                productoSeleccionado.setUrl(pm.guardarImagen(img));
            }

            if (pm.actualizarProducto(productoSeleccionado.getId(), productoSeleccionado)) {
                JOptionPane.showMessageDialog(this, "Producto actualizado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                //cargarTabla();
                limpiarFormulario();
                LayeredRegistro_producto.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo actualizar el producto.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_RegistrarActionPerformed
    
    public void CargarCombobox() {
        try {
            this.comboboxProveedor.setListadoProveedor(proveeedorManager.lista());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    public BufferedImage obtenerImagenDeLabel() {
        if (lblImagen.getIcon() != null && lblImagen.getIcon() instanceof ImageIcon) {
            Image imagen = ((ImageIcon) lblImagen.getIcon()).getImage();

            // Crear un BufferedImage compatible con la imagen
            BufferedImage buffered = new BufferedImage(
                    imagen.getWidth(null),
                    imagen.getHeight(null),
                    BufferedImage.TYPE_INT_ARGB // Puedes usar TYPE_INT_RGB si no necesitas transparencia
            );

            // Dibujar la imagen en el BufferedImage
            buffered.getGraphics().drawImage(imagen, 0, 0, null);
            return buffered;
        }
        return null; // No hay imagen en el label
    }
    
    private void limpiarFormulario() {
        TFNombre.setText("");
        SPPrecioCompra.setValue(0.0f);
        SPPrecioVenta.setValue(0.0f);
        SPStock.setValue(0.0f);
        if (CBProveedores.getItemCount() > 0) {
            CBProveedores.setSelectedIndex(0);
        }

        // Restablecer el label de la imagen
        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add_16750539.png")));
        lblImagen.setText("");

        // MUY IMPORTANTE: Resetear el estado a "nuevo registro"
        this.productoSeleccionado = null;
        //TBListaProductos.clearSelection();
        Registrar.setText("Registrar");
    }
    
    public void cargarDatosProductoSeleccionado() {
        
        if (productoSeleccionado != null) {

            TFNombre.setText(productoSeleccionado.getNombre());
            SPPrecioCompra.setValue(productoSeleccionado.getPrecioCompra());
            SPPrecioVenta.setValue(productoSeleccionado.getPrecioVenta());
            SPStock.setValue(productoSeleccionado.getStock());

            // Seleccionar el proveedor en el ComboBox
            Proveedor prov = productoSeleccionado.getProveedor();
            if (prov != null) {
                CBProveedores.setSelectedIndex(comboboxProveedor.getSelectProveedor(prov));
            }

            // Cargar la imagen
            cargarImagenEnLabel(productoSeleccionado.getUrl(), lblImagen);

            Registrar.setText("Guardar Cambios");
        }
    }
    
    private void cargarImagenEnLabel(String url, javax.swing.JLabel label) {
        if (url != null && !url.isEmpty()) {
            File archivo = new File(url);
            if (archivo.exists()) {
                try {
                    BufferedImage imagen = ImageIO.read(archivo);
                    Image escalada = imagen.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
                    label.setIcon(new ImageIcon(escalada));
                    label.setText("");
                } catch (Exception e) {
                    label.setText("Error al cargar imagen");
                    label.setIcon(null);
                }
            } else {
                label.setText("Imagen no encontrada");
                label.setIcon(null);
            }
        } else {
            label.setText("Sin imagen");
            label.setIcon(null);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBProveedores;
    private javax.swing.JLayeredPane LayeredRegistro_producto;
    private javax.swing.JButton Registrar;
    private javax.swing.JSpinner SPPrecioCompra;
    private javax.swing.JSpinner SPPrecioVenta;
    private javax.swing.JSpinner SPStock;
    private javax.swing.JTextField TFNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblImagen;
    // End of variables declaration//GEN-END:variables
}
